<?php

declare(strict_types=1);

namespace App\Tests;

use App\Entity\DutyAssignment;
use App\Entity\DutyAssignmentSource;
use App\Entity\DutySwapEvent;
use App\Entity\DutySwapNotification;
use App\Entity\DutySwapRequest;
use App\Repository\DutyAssignmentRepository;
use App\Repository\DutySwapRequestRepository;
use App\Repository\PlanningGenerationRepository;
use App\Repository\PlanningLineRepository;
use App\Repository\PlanningRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;

/**
 * Duty swaps between members (docs/duty-swaps.md, docs/decisions.md D178),
 * driven through the real API on top of CalendarWorkflowTestHelpers'
 * scenario (creator, admin, alice, bob — planning 2027-01-01 → 2027-05-01,
 * Europe/Brussels), generated by a real OR-Tools solve with an 11-hour
 * legal rest, then published, with the holders forced by the manager:
 *
 *   Tue 5 Jan   alice   (full day — 24h, 00:00 → 00:00)
 *   Wed 6 Jan   admin   (adjacent to the 5th: no rest in between)
 *   Sat 9 + Sun 10 Jan  admin  (one atomic block)
 *   Tue 12 Jan  bob
 *   Tue 19 Jan  admin
 *
 * So Alice ↔ Bob (5 ↔ 12) is valid; Adam can take Alice's 5th only by
 * giving her his 6th (the false-conflict case); Adam taking the 5th
 * against anything else breaks the rest.
 *
 * Expects a WebTestCase using ClockSensitiveTrait, time mocked before.
 */
trait DutySwapTestHelpers
{
    use CalendarWorkflowTestHelpers;

    /**
     * @return array<string, mixed>
     */
    private function swapScenario(KernelBrowser $client): array
    {
        $s = $this->pilotScenario($client);
        $this->prepareLine($s['planningId'], [['2027-01-05', '2027-01-06'], ['2027-01-06', '2027-01-07'], ['2027-01-12', '2027-01-13'], ['2027-01-19', '2027-01-20']], ['2027-01-09', '2027-01-10', '2027-01-11']);
        $this->generateNow($client, $s['planningId'], $s['creator'], ['legalMinRestEnabled' => true, 'legalMinRestHours' => 11]);
        self::assertResponseIsSuccessful();
        $this->setHolders($client, $s, [
            '2027-01-05' => 'alice@example.com',
            '2027-01-06' => 'admin@example.com',
            '2027-01-09' => 'admin@example.com',
            '2027-01-12' => 'bob@example.com',
            '2027-01-19' => 'admin@example.com',
        ]);
        $this->api($client, 'POST', "/api/plannings/{$s['planningId']}/publish", [], $s['creator']);
        self::assertResponseIsSuccessful();
        $this->nameUsers(['alice@example.com' => ['Alice', 'Martin'], 'bob@example.com' => ['Bob', 'Durand'], 'admin@example.com' => ['Adam', 'Leroy'], 'creator@example.com' => ['Claire', 'Dubois']]);

        return $s;
    }

    /**
     * Unassigns every duty whose holder differs, then assigns — never an
     * intermediate state the 11-hour rest would refuse.
     *
     * @param array<string, mixed>  $s
     * @param array<string, string> $holders date → email (a block by its first day)
     */
    private function setHolders(KernelBrowser $client, array $s, array $holders): void
    {
        $calendar = $this->currentCalendar($s['planningId']);
        foreach ($calendar as $key => $holder) {
            [, $date] = explode('|', $key);
            if (null !== $holder && ($holders[$date] ?? null) !== $holder && !\in_array($date, ['2027-01-10'], true)) {
                $this->unassignDuty($client, $s, $this->dutyOn($s['planningId'], $date));
                self::assertResponseIsSuccessful();
            }
        }
        $current = $this->holders($s);
        foreach ($holders as $date => $email) {
            if (($current[$date] ?? null) !== $email) {
                $this->reassignTo($client, $s, $this->dutyOn($s['planningId'], $date), $email);
                self::assertResponseIsSuccessful();
            }
        }
        $current = $this->holders($s);
        foreach ($holders as $date => $email) {
            self::assertSame($email, $current[$date], "Fixture: {$date} held by {$email}.");
        }
    }

    /**
     * @param array<string, array{0: string, 1: string}> $names
     */
    private function nameUsers(array $names): void
    {
        $em = static::getContainer()->get(EntityManagerInterface::class);
        foreach ($names as $email => [$first, $last]) {
            $user = static::getContainer()->get(UserRepository::class)->findOneByEmail($email);
            $user->setFirstName($first);
            $user->setLastName($last);
        }
        $em->flush();
    }

    private function userStableId(string $email): string
    {
        return (string) static::getContainer()->get(UserRepository::class)->findOneByEmail($email)->getStableId();
    }

    /**
     * "J'ai déjà convenu d'un échange": $token's unit on $date against $counterpartEmail's unit on $counterpartDate.
     *
     * @param array<string, mixed> $s
     *
     * @return array<string, mixed>
     */
    private function agreedRequest(KernelBrowser $client, array $s, string $token, string $date, string $counterpartEmail, string $counterpartDate, bool $acknowledged = true): array
    {
        return $this->api($client, 'POST', '/api/duty-swap-requests', [
            'dutyStableId' => $this->dutyOn($s['planningId'], $date),
            'kind' => 'AGREED',
            'recipientUserStableIds' => [$this->userStableId($counterpartEmail)],
            'counterpartDutyStableId' => $this->dutyOn($s['planningId'], $counterpartDate),
            'acknowledgedResponsibility' => $acknowledged,
        ], $token);
    }

    /**
     * "Je cherche quelqu'un avec qui échanger": to selected colleagues, or the whole line when $emails is null.
     *
     * @param array<string, mixed> $s
     * @param list<string>|null    $emails
     *
     * @return array<string, mixed>
     */
    private function searchRequest(KernelBrowser $client, array $s, string $token, string $date, ?array $emails): array
    {
        return $this->api($client, 'POST', '/api/duty-swap-requests', [
            'dutyStableId' => $this->dutyOn($s['planningId'], $date),
            'kind' => 'SEARCH',
            'audience' => null === $emails ? 'ALL' : 'SELECTED',
            'recipientUserStableIds' => array_map($this->userStableId(...), $emails ?? []),
            'acknowledgedResponsibility' => true,
        ], $token);
    }

    /**
     * @param array<string, mixed> $s
     *
     * @return array<string, mixed>
     */
    private function proposeOn(KernelBrowser $client, array $s, string $requestStableId, string $token, string $date): array
    {
        return $this->api($client, 'POST', "/api/duty-swap-requests/{$requestStableId}/proposals", ['dutyStableId' => $this->dutyOn($s['planningId'], $date)], $token);
    }

    /**
     * @return array<string, mixed>
     */
    private function decide(KernelBrowser $client, string $proposalStableId, string $action, string $token): array
    {
        return $this->api($client, 'POST', "/api/duty-swap-proposals/{$proposalStableId}/{$action}", [], $token);
    }

    /**
     * @return array<string, mixed>
     */
    private function requestDetail(KernelBrowser $client, string $requestStableId, string $token): array
    {
        return $this->api($client, 'GET', "/api/duty-swap-requests/{$requestStableId}", token: $token);
    }

    /**
     * @param array<string, mixed> $view a request view
     *
     * @return array<string, mixed>
     */
    private function proposalBy(array $view, string $authorEmail): array
    {
        $userStableId = $this->userStableId($authorEmail);
        foreach ($view['proposals'] as $proposal) {
            if ($proposal['author']['userStableId'] === $userStableId) {
                return $proposal;
            }
        }

        self::fail("No proposal by {$authorEmail}.");
    }

    /**
     * @return list<string> event types, in order
     */
    private function eventTypes(string $requestStableId): array
    {
        $em = static::getContainer()->get(EntityManagerInterface::class);
        $em->clear();
        $request = static::getContainer()->get(DutySwapRequestRepository::class)->findOneByStableId($requestStableId);

        return array_map(
            static fn (DutySwapEvent $event): string => $event->getType()->value,
            $em->getRepository(DutySwapEvent::class)->findBy(['request' => $request], ['occurredAt' => 'ASC', 'id' => 'ASC']),
        );
    }

    /**
     * @return list<DutySwapNotification>
     */
    private function notificationsOf(string $requestStableId, ?string $kind = null): array
    {
        $em = static::getContainer()->get(EntityManagerInterface::class);
        $em->clear();
        $request = static::getContainer()->get(DutySwapRequestRepository::class)->findOneByStableId($requestStableId);
        $criteria = ['request' => $request] + (null !== $kind ? ['kind' => $kind] : []);

        return $em->getRepository(DutySwapNotification::class)->findBy($criteria, ['id' => 'ASC']);
    }

    private function requestEntity(string $requestStableId): DutySwapRequest
    {
        static::getContainer()->get(EntityManagerInterface::class)->clear();

        return static::getContainer()->get(DutySwapRequestRepository::class)->findOneByStableId($requestStableId);
    }

    /**
     * Every current row of line 0, by local date.
     *
     * @return array<string, DutyAssignment>
     */
    private function currentRows(string $planningStableId): array
    {
        $container = static::getContainer();
        $container->get(EntityManagerInterface::class)->clear();
        $planning = $container->get(PlanningRepository::class)->findOneByStableId($planningStableId);
        $line = $container->get(PlanningLineRepository::class)->findByPlanning($planning)[0];
        $generation = $container->get(PlanningGenerationRepository::class)->findMostRecentCompletedByPlanningPeriod($line->getPlanningPeriod());
        $rows = [];
        foreach ($container->get(DutyAssignmentRepository::class)->findForGenerations([$generation]) as $row) {
            $rows[$row->getDuty()->getLocalDate()->format('Y-m-d')] = $row;
        }
        ksort($rows);

        return $rows;
    }

    private function sourceOn(string $planningStableId, string $date): DutyAssignmentSource
    {
        return $this->currentRows($planningStableId)[$date]->getSource();
    }

    /**
     * @param array<string, mixed> $s
     *
     * @return array<string, string|null> date → holder email, line 0 only
     */
    private function holders(array $s): array
    {
        $holders = [];
        foreach ($this->currentCalendar($s['planningId']) as $key => $email) {
            [$line, $date] = explode('|', $key);
            if ('0' === $line) {
                $holders[$date] = $email;
            }
        }

        return $holders;
    }
}
