<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Duty swaps between members (docs/duty-swaps.md, docs/decisions.md D178):
 * - `duty_swap_requests` / `duty_swap_request_recipients` / `duty_swap_proposals`:
 *   the workflow — never a source of truth for who holds a duty
 *   (DutyAssignment.current stays the only one);
 * - `duty_swap_events`: its append-only journal (trigger, like
 *   duty_assignment_events, D131);
 * - `duty_swap_notifications`: the email outbox (same delivery cycle as
 *   planning_publication_notifications, D172);
 * - `duty_assignment_events.swap_proposal_id`: links a calendar change to
 *   the accepted proposal that caused it (nullable, so existing rows are
 *   untouched — adding a column is DDL, never an UPDATE the append-only
 *   trigger would refuse).
 *
 * Database-level invariants, on top of the entities' own checks:
 * - at most one OPEN request per offered DutyAssignment row (a double
 *   submit can never open two requests for the same duty);
 * - at most one ACCEPTED proposal per request, and at most one PENDING
 *   proposal per (request, author);
 * - a closed request says when; a COMPLETED one names its proposal.
 *
 * New tables and one nullable column only: nothing existing is rewritten.
 */
final class Version20261008200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Duty swaps between members: requests, recipients, proposals, append-only events, email outbox (D178)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE duty_swap_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, kind VARCHAR(10) NOT NULL, audience VARCHAR(10) NOT NULL, status VARCHAR(10) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, planning_id INT NOT NULL, line_id INT NOT NULL, requester_id INT NOT NULL, requester_member_id INT NOT NULL, offered_duty_id INT NOT NULL, offered_assignment_id INT NOT NULL, accepted_proposal_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_duty_swap_requests_status ON duty_swap_requests (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_swap_requests_stable_id ON duty_swap_requests (stable_id)');
        $this->addSql('CREATE INDEX IDX_92378C1C3D865311 ON duty_swap_requests (planning_id)');
        $this->addSql('CREATE INDEX IDX_92378C1C4D7B7542 ON duty_swap_requests (line_id)');
        $this->addSql('CREATE INDEX IDX_92378C1CED442CF4 ON duty_swap_requests (requester_id)');
        $this->addSql('CREATE INDEX IDX_92378C1CC3AA3D7B ON duty_swap_requests (requester_member_id)');
        $this->addSql('CREATE INDEX IDX_92378C1C10E70BE6 ON duty_swap_requests (offered_duty_id)');
        $this->addSql('CREATE INDEX IDX_92378C1CA4D46268 ON duty_swap_requests (offered_assignment_id)');
        $this->addSql('CREATE INDEX IDX_92378C1C4309EB60 ON duty_swap_requests (accepted_proposal_id)');

        $this->addSql('CREATE TABLE duty_swap_request_recipients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, request_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_duty_swap_request_recipients_user ON duty_swap_request_recipients (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_swap_request_recipients ON duty_swap_request_recipients (request_id, user_id)');
        $this->addSql('CREATE INDEX IDX_D24C8098427EB8A5 ON duty_swap_request_recipients (request_id)');

        $this->addSql('CREATE TABLE duty_swap_proposals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, status VARCHAR(12) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, request_id INT NOT NULL, author_id INT NOT NULL, counterpart_member_id INT NOT NULL, counterpart_duty_id INT NOT NULL, counterpart_assignment_id INT NOT NULL, decided_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_duty_swap_proposals_status ON duty_swap_proposals (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_swap_proposals_stable_id ON duty_swap_proposals (stable_id)');
        $this->addSql('CREATE INDEX IDX_AD3EB5F8427EB8A5 ON duty_swap_proposals (request_id)');
        $this->addSql('CREATE INDEX IDX_AD3EB5F8F675F31B ON duty_swap_proposals (author_id)');
        $this->addSql('CREATE INDEX IDX_AD3EB5F82C751F29 ON duty_swap_proposals (counterpart_member_id)');
        $this->addSql('CREATE INDEX IDX_AD3EB5F815DFD8F0 ON duty_swap_proposals (counterpart_duty_id)');
        $this->addSql('CREATE INDEX IDX_AD3EB5F88C5A94C2 ON duty_swap_proposals (counterpart_assignment_id)');
        $this->addSql('CREATE INDEX IDX_AD3EB5F8E26B496B ON duty_swap_proposals (decided_by_id)');

        $this->addSql('CREATE TABLE duty_swap_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, type VARCHAR(30) NOT NULL, data JSON NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_id INT NOT NULL, proposal_id INT DEFAULT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_duty_swap_events_request ON duty_swap_events (request_id, occurred_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_swap_events_stable_id ON duty_swap_events (stable_id)');
        $this->addSql('CREATE INDEX IDX_1798A0EE427EB8A5 ON duty_swap_events (request_id)');
        $this->addSql('CREATE INDEX IDX_1798A0EEF4792058 ON duty_swap_events (proposal_id)');
        $this->addSql('CREATE INDEX IDX_1798A0EE10DAF24A ON duty_swap_events (actor_id)');

        $this->addSql('CREATE TABLE duty_swap_notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(30) NOT NULL, payload JSON NOT NULL, dedup_key VARCHAR(200) NOT NULL, status VARCHAR(10) NOT NULL, attempts INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, claimed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error VARCHAR(500) DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, request_id INT NOT NULL, proposal_id INT DEFAULT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_duty_swap_notifications_status ON duty_swap_notifications (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_swap_notifications_dedup ON duty_swap_notifications (dedup_key)');
        $this->addSql('CREATE INDEX IDX_2DB5A136427EB8A5 ON duty_swap_notifications (request_id)');
        $this->addSql('CREATE INDEX IDX_2DB5A136F4792058 ON duty_swap_notifications (proposal_id)');
        $this->addSql('CREATE INDEX IDX_2DB5A136E92F8F78 ON duty_swap_notifications (recipient_id)');

        $this->addSql('ALTER TABLE duty_swap_requests ADD CONSTRAINT FK_92378C1C3D865311 FOREIGN KEY (planning_id) REFERENCES plannings (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_requests ADD CONSTRAINT FK_92378C1C4D7B7542 FOREIGN KEY (line_id) REFERENCES planning_lines (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_requests ADD CONSTRAINT FK_92378C1CED442CF4 FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_requests ADD CONSTRAINT FK_92378C1CC3AA3D7B FOREIGN KEY (requester_member_id) REFERENCES planning_team_members (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_requests ADD CONSTRAINT FK_92378C1C10E70BE6 FOREIGN KEY (offered_duty_id) REFERENCES duties (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_requests ADD CONSTRAINT FK_92378C1CA4D46268 FOREIGN KEY (offered_assignment_id) REFERENCES duty_assignments (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_requests ADD CONSTRAINT FK_92378C1C4309EB60 FOREIGN KEY (accepted_proposal_id) REFERENCES duty_swap_proposals (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_request_recipients ADD CONSTRAINT FK_D24C8098427EB8A5 FOREIGN KEY (request_id) REFERENCES duty_swap_requests (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_request_recipients ADD CONSTRAINT FK_D24C8098A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_proposals ADD CONSTRAINT FK_AD3EB5F8427EB8A5 FOREIGN KEY (request_id) REFERENCES duty_swap_requests (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_proposals ADD CONSTRAINT FK_AD3EB5F8F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_proposals ADD CONSTRAINT FK_AD3EB5F82C751F29 FOREIGN KEY (counterpart_member_id) REFERENCES planning_team_members (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_proposals ADD CONSTRAINT FK_AD3EB5F815DFD8F0 FOREIGN KEY (counterpart_duty_id) REFERENCES duties (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_proposals ADD CONSTRAINT FK_AD3EB5F88C5A94C2 FOREIGN KEY (counterpart_assignment_id) REFERENCES duty_assignments (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_proposals ADD CONSTRAINT FK_AD3EB5F8E26B496B FOREIGN KEY (decided_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_events ADD CONSTRAINT FK_1798A0EE427EB8A5 FOREIGN KEY (request_id) REFERENCES duty_swap_requests (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_events ADD CONSTRAINT FK_1798A0EEF4792058 FOREIGN KEY (proposal_id) REFERENCES duty_swap_proposals (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_events ADD CONSTRAINT FK_1798A0EE10DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_notifications ADD CONSTRAINT FK_2DB5A136427EB8A5 FOREIGN KEY (request_id) REFERENCES duty_swap_requests (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_notifications ADD CONSTRAINT FK_2DB5A136F4792058 FOREIGN KEY (proposal_id) REFERENCES duty_swap_proposals (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_swap_notifications ADD CONSTRAINT FK_2DB5A136E92F8F78 FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');

        $this->addSql('ALTER TABLE duty_assignment_events ADD swap_proposal_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE duty_assignment_events ADD CONSTRAINT FK_F40DEC74FD7FDF1A FOREIGN KEY (swap_proposal_id) REFERENCES duty_swap_proposals (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F40DEC74FD7FDF1A ON duty_assignment_events (swap_proposal_id)');

        // Workflow invariants (see class docblock).
        $this->addSql("CREATE UNIQUE INDEX uniq_duty_swap_requests_open_offer ON duty_swap_requests (offered_assignment_id) WHERE status = 'OPEN'");
        $this->addSql("CREATE UNIQUE INDEX uniq_duty_swap_proposals_one_accepted ON duty_swap_proposals (request_id) WHERE status = 'ACCEPTED'");
        $this->addSql("CREATE UNIQUE INDEX uniq_duty_swap_proposals_one_pending_per_author ON duty_swap_proposals (request_id, author_id) WHERE status = 'PENDING'");
        $this->addSql("ALTER TABLE duty_swap_requests ADD CONSTRAINT chk_duty_swap_requests_kind CHECK (kind IN ('AGREED', 'SEARCH'))");
        $this->addSql("ALTER TABLE duty_swap_requests ADD CONSTRAINT chk_duty_swap_requests_audience CHECK (audience IN ('SELECTED', 'ALL'))");
        $this->addSql("ALTER TABLE duty_swap_requests ADD CONSTRAINT chk_duty_swap_requests_status CHECK (status IN ('OPEN', 'COMPLETED', 'REFUSED', 'CANCELLED', 'EXPIRED', 'OBSOLETE'))");
        $this->addSql("ALTER TABLE duty_swap_requests ADD CONSTRAINT chk_duty_swap_requests_closed_at CHECK ((status = 'OPEN') = (closed_at IS NULL))");
        $this->addSql("ALTER TABLE duty_swap_requests ADD CONSTRAINT chk_duty_swap_requests_accepted CHECK ((status = 'COMPLETED') = (accepted_proposal_id IS NOT NULL))");
        $this->addSql("ALTER TABLE duty_swap_proposals ADD CONSTRAINT chk_duty_swap_proposals_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REFUSED', 'WITHDRAWN', 'NOT_SELECTED', 'CANCELLED', 'EXPIRED', 'OBSOLETE'))");
        $this->addSql("ALTER TABLE duty_swap_proposals ADD CONSTRAINT chk_duty_swap_proposals_decided_at CHECK ((status = 'PENDING') = (decided_at IS NULL))");
        $this->addSql("ALTER TABLE duty_swap_notifications ADD CONSTRAINT chk_duty_swap_notifications_status CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED', 'CANCELLED'))");
        $this->addSql('ALTER TABLE duty_swap_notifications ADD CONSTRAINT chk_duty_swap_notifications_attempts CHECK (attempts >= 0)');
        $this->addSql("ALTER TABLE duty_swap_notifications ADD CONSTRAINT chk_duty_swap_notifications_sent_at CHECK ((status = 'SENT') = (sent_at IS NOT NULL))");

        $this->addSql(<<<'SQL'
            CREATE FUNCTION duty_swap_events_append_only() RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'duty_swap_events is append-only';
            END;
            $$ LANGUAGE plpgsql
        SQL);
        $this->addSql('CREATE TRIGGER trg_duty_swap_events_append_only BEFORE UPDATE OR DELETE ON duty_swap_events FOR EACH ROW EXECUTE FUNCTION duty_swap_events_append_only()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE duty_assignment_events DROP CONSTRAINT FK_F40DEC74FD7FDF1A');
        $this->addSql('DROP INDEX IDX_F40DEC74FD7FDF1A');
        $this->addSql('ALTER TABLE duty_assignment_events DROP swap_proposal_id');

        $this->addSql('DROP TRIGGER trg_duty_swap_events_append_only ON duty_swap_events');
        $this->addSql('DROP FUNCTION duty_swap_events_append_only()');
        $this->addSql('ALTER TABLE duty_swap_requests DROP CONSTRAINT FK_92378C1C4309EB60');
        $this->addSql('DROP TABLE duty_swap_notifications');
        $this->addSql('DROP TABLE duty_swap_events');
        $this->addSql('DROP TABLE duty_swap_proposals');
        $this->addSql('DROP TABLE duty_swap_request_recipients');
        $this->addSql('DROP TABLE duty_swap_requests');
    }
}
