<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Lot 2 — personal calendar (UserAvailabilityPeriod) and administrative
 * non-participation (TeamMemberNonParticipationPeriod), see
 * docs/availability.md. Also backfills a stable UUID identifier on
 * team_members (docs/decisions.md D056) the same way an earlier migration
 * did for users.
 *
 * Note: `doctrine:migrations:diff` also proposed dropping and recreating
 * several composite foreign keys, exclusion constraints and partial unique
 * indexes on unrelated tables (duties, duty_group_instances,
 * duty_pattern_components, planning_periods, fairness_periods,
 * team_member_participation_periods, planning_rule_sets) — false
 * positives: the schema comparator does not model hand-written composite
 * FKs/EXCLUDE constraints from Version20260915212500's raw SQL, so it
 * treats them as drift. None of that belongs in this migration and it has
 * been stripped out here; those constraints are untouched.
 */
final class Version20260916071843 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Personal calendar and administrative non-participation periods; backfills TeamMember.stableId.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE user_availability_periods (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
              ends_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
              type VARCHAR(20) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_user_availability_periods_stable_id ON user_availability_periods (stable_id)');
        $this->addSql('CREATE INDEX idx_user_availability_periods_user_range ON user_availability_periods (user_id, starts_at, ends_at)');
        $this->addSql(<<<'SQL'
            ALTER TABLE user_availability_periods ADD CONSTRAINT fk_user_availability_periods_user
              FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE team_member_non_participation_periods (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
              ends_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              team_member_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_non_participation_periods_stable_id ON team_member_non_participation_periods (stable_id)');
        $this->addSql('CREATE INDEX idx_non_participation_periods_member_range ON team_member_non_participation_periods (team_member_id, starts_at, ends_at)');
        $this->addSql(<<<'SQL'
            ALTER TABLE team_member_non_participation_periods ADD CONSTRAINT fk_non_participation_periods_team_member
              FOREIGN KEY (team_member_id) REFERENCES team_members (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);

        // Overlap-or-touch policy (docs/availability.md §Chevauchement):
        // stricter than FairnessPeriod/ParticipationPeriod's half-open
        // '[)' exclusion — here two periods whose endpoints merely touch
        // (one's ends_at equals the other's starts_at) must also be
        // rejected, hence the inclusive '[]' bounds: touching endpoints
        // then share a point, which && correctly reports as overlapping.
        // Partitioned by (user_id, type): UNAVAILABLE and PREFER_DUTY may
        // legitimately coexist on the same dates.
        $this->addSql(<<<'SQL'
            ALTER TABLE user_availability_periods ADD CONSTRAINT excl_user_availability_periods_no_overlap
              EXCLUDE USING gist (user_id WITH =, type WITH =, tstzrange(starts_at, ends_at, '[]') WITH &&)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE team_member_non_participation_periods ADD CONSTRAINT excl_non_participation_periods_no_overlap
              EXCLUDE USING gist (team_member_id WITH =, tstzrange(starts_at, ends_at, '[]') WITH &&)
        SQL);

        // Defense-in-depth CHECK constraints (already validated in entity constructors).
        $this->addSql('ALTER TABLE user_availability_periods ADD CONSTRAINT chk_user_availability_periods_dates CHECK (ends_at > starts_at)');
        $this->addSql('ALTER TABLE team_member_non_participation_periods ADD CONSTRAINT chk_non_participation_periods_dates CHECK (ends_at > starts_at)');

        // Added nullable first and backfilled, same reasoning as users.stable_id
        // in Version20260915212445: existing rows predate this column.
        $this->addSql('ALTER TABLE team_members ADD stable_id UUID DEFAULT NULL');
        $this->addSql('UPDATE team_members SET stable_id = gen_random_uuid() WHERE stable_id IS NULL');
        $this->addSql('ALTER TABLE team_members ALTER COLUMN stable_id SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_members_stable_id ON team_members (stable_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE team_members DROP CONSTRAINT IF EXISTS uniq_team_members_stable_id');
        $this->addSql('DROP INDEX IF EXISTS uniq_team_members_stable_id');
        $this->addSql('ALTER TABLE team_members DROP stable_id');

        $this->addSql('ALTER TABLE team_member_non_participation_periods DROP CONSTRAINT chk_non_participation_periods_dates');
        $this->addSql('ALTER TABLE user_availability_periods DROP CONSTRAINT chk_user_availability_periods_dates');
        $this->addSql('ALTER TABLE team_member_non_participation_periods DROP CONSTRAINT excl_non_participation_periods_no_overlap');
        $this->addSql('ALTER TABLE user_availability_periods DROP CONSTRAINT excl_user_availability_periods_no_overlap');

        $this->addSql('ALTER TABLE team_member_non_participation_periods DROP CONSTRAINT fk_non_participation_periods_team_member');
        $this->addSql('DROP TABLE team_member_non_participation_periods');
        $this->addSql('ALTER TABLE user_availability_periods DROP CONSTRAINT fk_user_availability_periods_user');
        $this->addSql('DROP TABLE user_availability_periods');
    }
}
