<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * SurgicalHub association (docs/surgicalhub-integration.md §4, docs/decisions.md D182):
 * - `surgical_hub_links`: one MedVue User ↔ one SurgicalHub account. At most
 *   one current (ACTIVE or SUSPENDED) row per User and one per SurgicalHub account (partial unique
 *   indexes, on top of SurgicalHubLinkService's checks);
 * - `surgical_hub_link_codes`: short-lived single-use codes, SHA-256 only;
 * - `surgical_hub_link_events`: append-only journal (trigger, like
 *   duty_swap_events) — never a code, never a secret.
 *
 * New tables only: nothing existing is touched.
 */
final class Version20261010090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'SurgicalHub association: links, single-use codes, append-only events (D182)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE surgical_hub_links (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, surgical_hub_user_id VARCHAR(64) NOT NULL, surgical_hub_display_name VARCHAR(200) NOT NULL, status VARCHAR(20) NOT NULL, linked_by_administrator BOOLEAN NOT NULL, linked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, suspended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_sync_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_successful_sync_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_sync_error VARCHAR(40) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_surgical_hub_links_stable_id ON surgical_hub_links (stable_id)');
        $this->addSql('CREATE INDEX idx_surgical_hub_links_user_id ON surgical_hub_links (user_id)');
        $this->addSql('CREATE INDEX idx_surgical_hub_links_status ON surgical_hub_links (status)');
        $this->addSql('ALTER TABLE surgical_hub_links ADD CONSTRAINT fk_surgical_hub_links_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE surgical_hub_links ADD CONSTRAINT chk_surgical_hub_links_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'REVOKED_LOCAL', 'REVOKED_REMOTE'))");
        $this->addSql("ALTER TABLE surgical_hub_links ADD CONSTRAINT chk_surgical_hub_links_revoked_at CHECK ((status IN ('ACTIVE', 'SUSPENDED')) = (revoked_at IS NULL))");
        $this->addSql("CREATE UNIQUE INDEX uniq_surgical_hub_links_active_user ON surgical_hub_links (user_id) WHERE status IN ('ACTIVE', 'SUSPENDED')");
        $this->addSql("CREATE UNIQUE INDEX uniq_surgical_hub_links_active_surgical_hub_user ON surgical_hub_links (surgical_hub_user_id) WHERE status IN ('ACTIVE', 'SUSPENDED')");

        $this->addSql('CREATE TABLE surgical_hub_link_codes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_surgical_hub_link_codes_code_hash ON surgical_hub_link_codes (code_hash)');
        $this->addSql('CREATE INDEX idx_surgical_hub_link_codes_user_id ON surgical_hub_link_codes (user_id)');
        $this->addSql('ALTER TABLE surgical_hub_link_codes ADD CONSTRAINT fk_surgical_hub_link_codes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE surgical_hub_link_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(40) NOT NULL, surgical_hub_user_id VARCHAR(64) DEFAULT NULL, actor_label VARCHAR(200) DEFAULT NULL, details JSON DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, link_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_surgical_hub_link_events_user_id ON surgical_hub_link_events (user_id)');
        $this->addSql('CREATE INDEX idx_surgical_hub_link_events_link_id ON surgical_hub_link_events (link_id)');
        $this->addSql('ALTER TABLE surgical_hub_link_events ADD CONSTRAINT fk_surgical_hub_link_events_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE surgical_hub_link_events ADD CONSTRAINT fk_surgical_hub_link_events_link FOREIGN KEY (link_id) REFERENCES surgical_hub_links (id) ON DELETE RESTRICT NOT DEFERRABLE');

        $this->addSql(<<<'SQL'
            CREATE FUNCTION surgical_hub_link_events_append_only() RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'surgical_hub_link_events is append-only';
            END;
            $$ LANGUAGE plpgsql
        SQL);
        $this->addSql('CREATE TRIGGER trg_surgical_hub_link_events_append_only BEFORE UPDATE OR DELETE ON surgical_hub_link_events FOR EACH ROW EXECUTE FUNCTION surgical_hub_link_events_append_only()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TRIGGER trg_surgical_hub_link_events_append_only ON surgical_hub_link_events');
        $this->addSql('DROP FUNCTION surgical_hub_link_events_append_only()');
        $this->addSql('DROP TABLE surgical_hub_link_events');
        $this->addSql('DROP TABLE surgical_hub_link_codes');
        $this->addSql('DROP TABLE surgical_hub_links');
    }
}
