<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Personalised republication emails (docs/decisions.md D172):
 * `planning_publication_notifications`, the outbox of the emails a
 * PlanningPublication owes — one row per (publication, user), written in the
 * publication's own transaction, mutable delivery state (PENDING → SENDING →
 * SENT / FAILED / CANCELLED), retried by `app:publication-notifications:retry`.
 *
 * New table only. Existing publications keep their append-only
 * `planning_publication_deliveries` audit and get no notification row: their
 * emails were already attempted, and the content of a past republication
 * email was never stored — nothing is reconstructed, nothing is re-sent.
 */
final class Version20260930090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Publication notifications outbox: per-recipient, retriable, at-most-once republication emails (D172)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE planning_publication_notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, changes JSON DEFAULT NULL, status VARCHAR(10) NOT NULL, attempts INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, claimed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, publication_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_planning_publication_notifications_status ON planning_publication_notifications (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_publication_notifications_user ON planning_publication_notifications (publication_id, user_id)');
        $this->addSql('CREATE INDEX IDX_6B8AFE8A38B217A7 ON planning_publication_notifications (publication_id)');
        $this->addSql('CREATE INDEX IDX_6B8AFE8AA76ED395 ON planning_publication_notifications (user_id)');
        $this->addSql('ALTER TABLE planning_publication_notifications ADD CONSTRAINT FK_6B8AFE8A38B217A7 FOREIGN KEY (publication_id) REFERENCES planning_publications (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_publication_notifications ADD CONSTRAINT FK_6B8AFE8AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE planning_publication_notifications ADD CONSTRAINT chk_planning_publication_notifications_status CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED', 'CANCELLED'))");
        $this->addSql('ALTER TABLE planning_publication_notifications ADD CONSTRAINT chk_planning_publication_notifications_attempts CHECK (attempts >= 0)');
        // A sent email says when; nothing else does.
        $this->addSql("ALTER TABLE planning_publication_notifications ADD CONSTRAINT chk_planning_publication_notifications_sent_at CHECK ((status = 'SENT') = (sent_at IS NOT NULL))");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE planning_publication_notifications');
    }
}
