<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Asynchronous engine jobs (docs/decisions.md D149):
 *
 * - `planning_jobs`: one row per "Générer le planning" / "Compléter
 *   automatiquement" request, followed by the screen. The partial unique
 *   index is the concurrency rule itself: at most one QUEUED/RUNNING job per
 *   Planning, whatever the number of clicks, tabs or managers.
 * - `messenger_messages`: the Symfony Messenger Doctrine transport table
 *   (queues `planning_jobs` and `failed`), created here rather than by the
 *   transport (`auto_setup=0`) so production schema changes only ever come
 *   from migrations.
 * - Before this lot a generation ran inside the web request: a request cut
 *   by the 30 s execution limit left its generation SOLVING forever. No
 *   solve can be running when this migration runs (the synchronous path is
 *   gone with the deployment that ships it), so every SOLVING generation is
 *   such a leftover: marked FAILED (UPDATE, reviewed per
 *   docs/deployment.md §1 step 6 — it only touches rows stuck in SOLVING).
 */
final class Version20260927170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Asynchronous planning jobs and the Messenger transport table (D149)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE planning_jobs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, kind VARCHAR(10) NOT NULL, status VARCHAR(10) NOT NULL, rest_policy JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, heartbeat_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, outcome JSON DEFAULT NULL, failure_code VARCHAR(40) DEFAULT NULL, failure_detail TEXT DEFAULT NULL, planning_id INT NOT NULL, requested_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_jobs_stable_id ON planning_jobs (stable_id)');
        $this->addSql('CREATE INDEX idx_planning_jobs_planning ON planning_jobs (planning_id, created_at)');
        $this->addSql('CREATE INDEX idx_planning_jobs_status ON planning_jobs (status)');
        $this->addSql('CREATE INDEX IDX_6045658B4DA1E751 ON planning_jobs (requested_by_id)');
        $this->addSql('ALTER TABLE planning_jobs ADD CONSTRAINT FK_6045658B3D865311 FOREIGN KEY (planning_id) REFERENCES plannings (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_jobs ADD CONSTRAINT FK_6045658B4DA1E751 FOREIGN KEY (requested_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE planning_jobs ADD CONSTRAINT chk_planning_jobs_kind CHECK (kind IN ('GENERATE', 'COMPLETE'))");
        $this->addSql("ALTER TABLE planning_jobs ADD CONSTRAINT chk_planning_jobs_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED'))");
        $this->addSql("CREATE UNIQUE INDEX uniq_planning_jobs_one_active ON planning_jobs (planning_id) WHERE status IN ('QUEUED', 'RUNNING')");

        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');

        $this->addSql("UPDATE planning_generations SET status = 'FAILED', failure_reason = 'Interrupted: the synchronous request that ran it was cut before it finished (before D149).', lock_version = lock_version + 1 WHERE status = 'SOLVING'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE planning_jobs');
    }
}
