<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Configurable weekly structure per PlanningLine, generic equity families
 * (docs/decisions.md D135): a new `allocation_families` catalogue
 * (team-scoped, exactly like `duty_types`), referenced optionally by
 * `duty_patterns.family_id` (nullable — every pre-D135 pattern has none,
 * and a pattern with no family simply never feeds the new
 * ALLOCATION_FAMILY fairness dimension), and a new `duties.pattern_id`
 * (nullable) so a solo (ungrouped) Duty materialized from a one-component
 * pattern can still carry a family — a grouped Duty already reaches its
 * pattern via `group_instance_id`, but denormalizing the direct reference
 * here gives every Duty, grouped or solo, one single lookup path.
 */
final class Version20260924090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add allocation_families catalogue and duty_patterns.family_id / duties.pattern_id (D135)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE allocation_families (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, team_id INT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(150) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_allocation_families_stable_id ON allocation_families (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_allocation_families_team_code ON allocation_families (team_id, code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_allocation_families_id_team_id ON allocation_families (id, team_id)');
        $this->addSql('CREATE INDEX idx_allocation_families_team_id ON allocation_families (team_id)');
        $this->addSql('ALTER TABLE allocation_families ADD CONSTRAINT fk_allocation_families_team FOREIGN KEY (team_id) REFERENCES planning_teams (id) ON DELETE RESTRICT NOT DEFERRABLE');

        $this->addSql('ALTER TABLE duty_patterns ADD family_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_duty_patterns_family_id ON duty_patterns (family_id)');
        $this->addSql('ALTER TABLE duty_patterns ADD CONSTRAINT fk_duty_patterns_family FOREIGN KEY (family_id) REFERENCES allocation_families (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql(<<<'SQL'
            ALTER TABLE duty_patterns ADD CONSTRAINT fk_duty_patterns_family_team
              FOREIGN KEY (family_id, team_id) REFERENCES allocation_families (id, team_id) NOT DEFERRABLE
        SQL);

        $this->addSql('ALTER TABLE duties ADD pattern_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_duties_pattern_id ON duties (pattern_id)');
        $this->addSql('ALTER TABLE duties ADD CONSTRAINT fk_duties_pattern FOREIGN KEY (pattern_id) REFERENCES duty_patterns (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql(<<<'SQL'
            ALTER TABLE duties ADD CONSTRAINT fk_duties_pattern_team
              FOREIGN KEY (pattern_id, team_id) REFERENCES duty_patterns (id, team_id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE duties DROP CONSTRAINT fk_duties_pattern_team');
        $this->addSql('ALTER TABLE duties DROP CONSTRAINT fk_duties_pattern');
        $this->addSql('DROP INDEX idx_duties_pattern_id');
        $this->addSql('ALTER TABLE duties DROP pattern_id');

        $this->addSql('ALTER TABLE duty_patterns DROP CONSTRAINT fk_duty_patterns_family_team');
        $this->addSql('ALTER TABLE duty_patterns DROP CONSTRAINT fk_duty_patterns_family');
        $this->addSql('DROP INDEX idx_duty_patterns_family_id');
        $this->addSql('ALTER TABLE duty_patterns DROP family_id');

        $this->addSql('DROP TABLE allocation_families');
    }
}
