<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Lot 6E orchestration (docs/decisions.md D106):
 *
 * - `solver_parameter_sets` — new, versioned, append-only, system-wide.
 *   Seeded with version 1 (`timeout_seconds = 60`, `num_workers = 1`) in
 *   `up()` — a real, documented, version-controlled value, never a hidden
 *   PHP constant (see the migration's own INSERT and D106 for the
 *   justification of 60s/phase).
 * - `planning_generations` gains: `lock_version` (Doctrine optimistic
 *   locking, the real SNAPSHOTTED → SOLVING concurrency claim),
 *   `mode`, and the full solver-run metadata set (`algorithm_version`
 *   through `generated_at`) — all nullable except `lock_version`/`mode`,
 *   since they stay unset until a real solve concludes.
 *
 * Hand-pruned from the raw `doctrine:migrations:diff` output — as with
 * every migration since D051, composite-FK/partial-index noise from
 * earlier "hardening" migrations is left untouched; none of it references
 * `planning_generations` or the two new tables/columns here.
 */
final class Version20260919090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Lot 6E: SolverParameterSet + PlanningGeneration solver-run metadata (lock_version, mode, algorithm/solver/seed/snapshotHash, statuses, objectiveValues/optimality, duration, timeout, failureReason, generatedAt).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE solver_parameter_sets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, version INT NOT NULL, timeout_seconds INT NOT NULL, num_workers INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_solver_parameter_sets_stable_id ON solver_parameter_sets (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_solver_parameter_sets_version ON solver_parameter_sets (version)');

        // Seed version 1 — a real, documented engineering choice (D106),
        // not a hidden constant: 60s per individual CP-SAT Solve() call
        // (worst case ~11 calls per STRICT/PARTIAL subprocess run, see
        // OrToolsPlanningSolver::PROCESS_TIMEOUT_MULTIPLIER), numWorkers=1
        // required for determinism (docs/planning-solver.md §20).
        $this->addSql('INSERT INTO solver_parameter_sets (stable_id, version, timeout_seconds, num_workers, created_at) VALUES (gen_random_uuid(), 1, 60, 1, NOW())');

        $this->addSql('ALTER TABLE planning_generations ADD lock_version INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD mode VARCHAR(20) DEFAULT \'GENERATE\' NOT NULL');
        $this->addSql('ALTER TABLE planning_generations ALTER mode DROP DEFAULT');
        $this->addSql('ALTER TABLE planning_generations ADD algorithm_version VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD solver_type VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD solver_version VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD solver_parameter_set_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD seed VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD snapshot_hash VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD strict_solver_status VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD partial_solver_status VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD coverage_status VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD objective_values JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD optimality JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD solve_duration_ms INT DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD timeout_hit BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD failure_reason VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD generated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE planning_generations ADD CONSTRAINT FK_planning_generations_solver_parameter_set FOREIGN KEY (solver_parameter_set_id) REFERENCES solver_parameter_sets (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_planning_generations_solver_parameter_set_id ON planning_generations (solver_parameter_set_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE planning_generations DROP CONSTRAINT FK_planning_generations_solver_parameter_set');
        $this->addSql('DROP INDEX idx_planning_generations_solver_parameter_set_id');
        $this->addSql('ALTER TABLE planning_generations DROP lock_version');
        $this->addSql('ALTER TABLE planning_generations DROP mode');
        $this->addSql('ALTER TABLE planning_generations DROP algorithm_version');
        $this->addSql('ALTER TABLE planning_generations DROP solver_type');
        $this->addSql('ALTER TABLE planning_generations DROP solver_version');
        $this->addSql('ALTER TABLE planning_generations DROP solver_parameter_set_id');
        $this->addSql('ALTER TABLE planning_generations DROP seed');
        $this->addSql('ALTER TABLE planning_generations DROP snapshot_hash');
        $this->addSql('ALTER TABLE planning_generations DROP strict_solver_status');
        $this->addSql('ALTER TABLE planning_generations DROP partial_solver_status');
        $this->addSql('ALTER TABLE planning_generations DROP coverage_status');
        $this->addSql('ALTER TABLE planning_generations DROP objective_values');
        $this->addSql('ALTER TABLE planning_generations DROP optimality');
        $this->addSql('ALTER TABLE planning_generations DROP solve_duration_ms');
        $this->addSql('ALTER TABLE planning_generations DROP timeout_hit');
        $this->addSql('ALTER TABLE planning_generations DROP failure_reason');
        $this->addSql('ALTER TABLE planning_generations DROP generated_at');
        $this->addSql('DROP TABLE solver_parameter_sets');
    }
}
