<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Versioned demand policy of a PlanningLine (docs/decisions.md D162):
 *
 * - `planning_line_demand_policies`: one row per version, created ACTIVE,
 *   later RETIRED — never edited. At most one ACTIVE per line (partial
 *   unique index, hand-added: not expressible in the Doctrine mapping,
 *   same as the rule sets). The source line is kept as a relation (SET NULL
 *   if that line is deleted) AND as a stable-id value (never lost).
 * - `planning_line_demand_triggers`: one row per person (User, never a
 *   stint) per version: an ISO weekday bitmask and an increment.
 *
 * No existing line gets a policy: "no policy" means INDEPENDENT, the
 * behaviour every line already has.
 */
final class Version20260928150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Versioned demand policies and triggers of planning lines (D162)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE planning_line_demand_policies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, version INT NOT NULL, mode VARCHAR(40) NOT NULL, source_line_stable_id UUID DEFAULT NULL, status VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, retired_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, target_line_id INT NOT NULL, source_line_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_demand_policies_source_line ON planning_line_demand_policies (source_line_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_demand_policies_stable_id ON planning_line_demand_policies (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_demand_policies_line_version ON planning_line_demand_policies (target_line_id, version)');
        $this->addSql('CREATE INDEX IDX_6BE5F7E68613CC29 ON planning_line_demand_policies (target_line_id)');
        $this->addSql('CREATE INDEX IDX_6BE5F7E6B03A8386 ON planning_line_demand_policies (created_by_id)');
        $this->addSql('ALTER TABLE planning_line_demand_policies ADD CONSTRAINT FK_6BE5F7E68613CC29 FOREIGN KEY (target_line_id) REFERENCES planning_lines (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_line_demand_policies ADD CONSTRAINT FK_6BE5F7E64A4CD2A FOREIGN KEY (source_line_id) REFERENCES planning_lines (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_line_demand_policies ADD CONSTRAINT FK_6BE5F7E6B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        // At most one policy in force per line.
        $this->addSql("CREATE UNIQUE INDEX uniq_demand_policies_one_active ON planning_line_demand_policies (target_line_id) WHERE status = 'ACTIVE'");
        // Defense in depth, already enforced by the entity/service.
        $this->addSql("ALTER TABLE planning_line_demand_policies ADD CONSTRAINT chk_demand_policies_mode CHECK (mode IN ('INDEPENDENT', 'CONDITIONAL_ON_SOURCE_ASSIGNMENT'))");
        $this->addSql("ALTER TABLE planning_line_demand_policies ADD CONSTRAINT chk_demand_policies_status CHECK (status IN ('ACTIVE', 'RETIRED'))");
        $this->addSql('ALTER TABLE planning_line_demand_policies ADD CONSTRAINT chk_demand_policies_version CHECK (version >= 1)');
        $this->addSql("ALTER TABLE planning_line_demand_policies ADD CONSTRAINT chk_demand_policies_retired_at CHECK ((status = 'ACTIVE') = (retired_at IS NULL))");
        // A conditional version always names its source (as a value, forever)...
        $this->addSql("ALTER TABLE planning_line_demand_policies ADD CONSTRAINT chk_demand_policies_source_value CHECK ((mode = 'INDEPENDENT') = (source_line_stable_id IS NULL))");
        // ...and, while in force, still points to a real line — deleting the source of an ACTIVE conditional policy
        // is refused by the application first (line_is_demand_source), and by this CHECK if SET NULL ever fired.
        $this->addSql("ALTER TABLE planning_line_demand_policies ADD CONSTRAINT chk_demand_policies_active_source CHECK (status = 'RETIRED' OR (mode = 'INDEPENDENT') = (source_line_id IS NULL))");
        $this->addSql('ALTER TABLE planning_line_demand_policies ADD CONSTRAINT chk_demand_policies_not_self CHECK (source_line_id IS NULL OR source_line_id <> target_line_id)');

        $this->addSql('CREATE TABLE planning_line_demand_triggers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, weekday_mask SMALLINT NOT NULL, increment SMALLINT NOT NULL, policy_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_demand_triggers_user ON planning_line_demand_triggers (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_demand_triggers_stable_id ON planning_line_demand_triggers (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_demand_triggers_policy_user ON planning_line_demand_triggers (policy_id, user_id)');
        $this->addSql('CREATE INDEX IDX_85A0C1652D29E3C6 ON planning_line_demand_triggers (policy_id)');
        $this->addSql('ALTER TABLE planning_line_demand_triggers ADD CONSTRAINT FK_85A0C1652D29E3C6 FOREIGN KEY (policy_id) REFERENCES planning_line_demand_policies (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_line_demand_triggers ADD CONSTRAINT FK_85A0C165A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_line_demand_triggers ADD CONSTRAINT chk_demand_triggers_weekdays CHECK (weekday_mask BETWEEN 1 AND 127)');
        $this->addSql('ALTER TABLE planning_line_demand_triggers ADD CONSTRAINT chk_demand_triggers_increment CHECK (increment >= 1)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE planning_line_demand_triggers');
        $this->addSql('DROP TABLE planning_line_demand_policies');
    }
}
