<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Dynamic calendar (docs/decisions.md D131): `duty_assignments` becomes
 * replaceable without ever losing history. Existing rows all become the
 * current one for their (generation, duty) — nothing about prod data
 * changes in meaning. The old strict unique constraint is replaced by a
 * partial unique index scoped to `current`, so a superseded row can keep
 * existing side by side with its replacement. `duty_assignment_events` is
 * a new, append-only audit trail (same trigger pattern as
 * planning_availability_reminders, D127) — never edited nor deleted.
 */
final class Version20260923120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add duty_assignments.current (replaceable, D131) and duty_assignment_events (append-only)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE duty_assignments ADD current BOOLEAN NOT NULL DEFAULT true');
        $this->addSql('DROP INDEX uniq_duty_assignments_generation_duty');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_assignments_generation_duty_current ON duty_assignments (generation_id, duty_id) WHERE current');

        $this->addSql('CREATE TABLE duty_assignment_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, was_published BOOLEAN NOT NULL, planning_id INT NOT NULL, generation_id INT NOT NULL, duty_id INT NOT NULL, previous_assignment_id INT DEFAULT NULL, new_assignment_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_assignment_events_stable_id ON duty_assignment_events (stable_id)');
        $this->addSql('CREATE INDEX idx_duty_assignment_events_planning ON duty_assignment_events (planning_id, occurred_at)');
        $this->addSql('CREATE INDEX idx_duty_assignment_events_duty ON duty_assignment_events (duty_id)');
        $this->addSql('ALTER TABLE duty_assignment_events ADD CONSTRAINT fk_duty_assignment_events_planning FOREIGN KEY (planning_id) REFERENCES plannings (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_assignment_events ADD CONSTRAINT fk_duty_assignment_events_generation FOREIGN KEY (generation_id) REFERENCES planning_generations (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_assignment_events ADD CONSTRAINT fk_duty_assignment_events_duty FOREIGN KEY (duty_id) REFERENCES duties (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_assignment_events ADD CONSTRAINT fk_duty_assignment_events_previous FOREIGN KEY (previous_assignment_id) REFERENCES duty_assignments (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_assignment_events ADD CONSTRAINT fk_duty_assignment_events_new FOREIGN KEY (new_assignment_id) REFERENCES duty_assignments (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_assignment_events ADD CONSTRAINT fk_duty_assignment_events_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');

        $this->addSql(<<<'SQL'
            CREATE FUNCTION duty_assignment_events_append_only() RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'duty_assignment_events is append-only';
            END;
            $$ LANGUAGE plpgsql
        SQL);
        $this->addSql('CREATE TRIGGER trg_duty_assignment_events_append_only BEFORE UPDATE OR DELETE ON duty_assignment_events FOR EACH ROW EXECUTE FUNCTION duty_assignment_events_append_only()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TRIGGER trg_duty_assignment_events_append_only ON duty_assignment_events');
        $this->addSql('DROP FUNCTION duty_assignment_events_append_only()');
        $this->addSql('DROP TABLE duty_assignment_events');

        $this->addSql('DROP INDEX uniq_duty_assignments_generation_duty_current');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_assignments_generation_duty ON duty_assignments (generation_id, duty_id)');
        $this->addSql('ALTER TABLE duty_assignments DROP current');
    }
}
