<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Secret subscription address of a User's duty calendar (docs/decisions.md
 * D170): `calendar_feeds`, at most one active (non-revoked) row per user.
 * New table only.
 */
final class Version20260929140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Calendar subscription feeds (ICS) of a user\'s duties (D170)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE calendar_feeds (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, last_fetched_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_calendar_feeds_token ON calendar_feeds (token)');
        $this->addSql('CREATE INDEX idx_calendar_feeds_user_id ON calendar_feeds (user_id)');
        $this->addSql('ALTER TABLE calendar_feeds ADD CONSTRAINT FK_CALENDAR_FEEDS_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        // One active address per user: regenerating revokes the previous one first.
        $this->addSql('CREATE UNIQUE INDEX uniq_calendar_feeds_active_user ON calendar_feeds (user_id) WHERE revoked_at IS NULL');
        $this->addSql("ALTER TABLE calendar_feeds ADD CONSTRAINT chk_calendar_feeds_token CHECK (token ~ '^[0-9a-f]{64}$')");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE calendar_feeds');
    }
}
