<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Platform administration V1 (docs/admin.md, docs/decisions.md D174-D177).
 *
 *  - users.platform_admin: the global ROLE_PLATFORM_ADMIN, independent of
 *    every team role, false for every existing account (never granted by a
 *    migration: the first grant is a console command).
 *  - user_activity_days: one row per user and active day (Europe/Brussels),
 *    fed by login and refresh-token rotation. Backfilled from
 *    refresh_tokens.created_at — each row of that table is exactly one login
 *    or one rotation, so the history is real, not reconstructed.
 *  - platform_audit_events: append-only audit of sensitive administrative
 *    actions. Registrations already on file are backfilled as
 *    USER_REGISTERED (context.backfilled = true), dated by users.created_at.
 *  - technical_error_events: unexpected server errors (class + route only,
 *    never a message), purged after 90 days — a technical log, not an audit.
 *
 * No UPDATE or DELETE of existing rows: only additions.
 */
final class Version20261008100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Platform administration: users.platform_admin, user_activity_days, platform_audit_events, technical_error_events';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD platform_admin BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('CREATE INDEX idx_users_created_at ON users (created_at)');
        $this->addSql('CREATE INDEX idx_plannings_created_at ON plannings (created_at)');

        $this->addSql('CREATE TABLE user_activity_days (user_id INT NOT NULL, activity_date DATE NOT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (user_id, activity_date))');
        $this->addSql('CREATE INDEX idx_user_activity_days_date ON user_activity_days (activity_date)');
        $this->addSql('ALTER TABLE user_activity_days ADD CONSTRAINT fk_user_activity_days_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_activity_days ADD CONSTRAINT chk_user_activity_days_seen CHECK (last_seen_at >= first_seen_at)');
        // Same day boundary as App\Service\Admin\PlatformTime::TIMEZONE.
        $this->addSql(<<<'SQL'
            INSERT INTO user_activity_days (user_id, activity_date, first_seen_at, last_seen_at)
            SELECT user_id,
                   ((created_at AT TIME ZONE 'UTC') AT TIME ZONE 'Europe/Brussels')::date,
                   MIN(created_at),
                   MAX(created_at)
            FROM refresh_tokens
            GROUP BY 1, 2
        SQL);

        $this->addSql('CREATE TABLE platform_audit_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(40) NOT NULL, outcome VARCHAR(10) NOT NULL, actor_kind VARCHAR(10) NOT NULL, actor_id INT DEFAULT NULL, target_user_id INT DEFAULT NULL, context JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_platform_audit_events_stable_id ON platform_audit_events (stable_id)');
        $this->addSql('CREATE INDEX idx_platform_audit_events_occurred ON platform_audit_events (occurred_at)');
        $this->addSql('CREATE INDEX idx_platform_audit_events_type ON platform_audit_events (type, occurred_at)');
        $this->addSql('CREATE INDEX idx_platform_audit_events_target ON platform_audit_events (target_user_id, occurred_at)');
        $this->addSql('CREATE INDEX idx_platform_audit_events_actor ON platform_audit_events (actor_id)');
        $this->addSql('ALTER TABLE platform_audit_events ADD CONSTRAINT fk_platform_audit_events_actor FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE platform_audit_events ADD CONSTRAINT fk_platform_audit_events_target FOREIGN KEY (target_user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE platform_audit_events ADD CONSTRAINT chk_platform_audit_events_type CHECK (type IN ('USER_REGISTERED', 'USER_DEACTIVATED', 'USER_REACTIVATED', 'USER_SESSIONS_REVOKED', 'PLATFORM_ADMIN_GRANTED', 'PLATFORM_ADMIN_REVOKED', 'PASSWORD_RESET_COMPLETED'))");
        $this->addSql("ALTER TABLE platform_audit_events ADD CONSTRAINT chk_platform_audit_events_outcome CHECK (outcome IN ('SUCCESS', 'DENIED', 'FAILURE'))");
        $this->addSql("ALTER TABLE platform_audit_events ADD CONSTRAINT chk_platform_audit_events_actor_kind CHECK (actor_kind IN ('USER', 'CONSOLE', 'SYSTEM'))");
        $this->addSql("ALTER TABLE platform_audit_events ADD CONSTRAINT chk_platform_audit_events_actor CHECK ((actor_kind = 'USER') = (actor_id IS NOT NULL))");
        $this->addSql(<<<'SQL'
            INSERT INTO platform_audit_events (stable_id, occurred_at, type, outcome, actor_kind, actor_id, target_user_id, context)
            SELECT gen_random_uuid(), created_at, 'USER_REGISTERED', 'SUCCESS', 'USER', id, id, '{"backfilled": true}'::json
            FROM users
            ORDER BY created_at, id
        SQL);
        // Append-only: an audit entry is never edited nor removed.
        $this->addSql(<<<'SQL'
            CREATE FUNCTION platform_audit_events_append_only() RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'platform_audit_events is append-only';
            END;
            $$ LANGUAGE plpgsql
        SQL);
        $this->addSql('CREATE TRIGGER trg_platform_audit_events_append_only BEFORE UPDATE OR DELETE ON platform_audit_events FOR EACH ROW EXECUTE FUNCTION platform_audit_events_append_only()');

        $this->addSql('CREATE TABLE technical_error_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source VARCHAR(10) NOT NULL, exception_class VARCHAR(255) NOT NULL, route VARCHAR(255) DEFAULT NULL, http_method VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_technical_error_events_occurred ON technical_error_events (occurred_at)');
        $this->addSql("ALTER TABLE technical_error_events ADD CONSTRAINT chk_technical_error_events_source CHECK (source IN ('HTTP', 'WORKER'))");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE technical_error_events');
        $this->addSql('DROP TRIGGER trg_platform_audit_events_append_only ON platform_audit_events');
        $this->addSql('DROP FUNCTION platform_audit_events_append_only()');
        $this->addSql('DROP TABLE platform_audit_events');
        $this->addSql('DROP TABLE user_activity_days');
        $this->addSql('DROP INDEX idx_plannings_created_at');
        $this->addSql('DROP INDEX idx_users_created_at');
        $this->addSql('ALTER TABLE users DROP platform_admin');
    }
}
