<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A conditional line's generation freezes its demand in the snapshot
 * (docs/decisions.md D164):
 *
 * - `planning_snapshot_demand_policies` (at most one per snapshot) and
 *   `planning_snapshot_demand_triggers`: the policy version, the source
 *   line, the source generation that was read, and a copy of every
 *   trigger;
 * - `planning_snapshot_demand_decisions`: one row per conditional duty —
 *   its day's evaluation and the decision for its unit (required true /
 *   false / NULL = undetermined, never silently "not required").
 *
 * New tables only: an existing snapshot (independent line) has none.
 */
final class Version20260929090000 extends AbstractMigration
{
    private const REASONS = "'INTRINSIC_REQUIRED', 'INTRINSIC_OPTIONAL', 'TRIGGERED', 'TRIGGERED_BY_BLOCK', 'SOURCE_LINE_NOT_GENERATED', 'SOURCE_UNASSIGNED', 'HOLDER_HAS_NO_TRIGGER', 'WEEKDAY_NOT_TRIGGERED', 'LINE_NOT_CONDITIONAL', 'NOT_IN_SNAPSHOT'";

    public function getDescription(): string
    {
        return 'Frozen demand policy and demand decisions of a conditional line generation (D164)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE planning_snapshot_demand_policies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, policy_stable_id UUID NOT NULL, policy_version INT NOT NULL, source_line_stable_id UUID NOT NULL, source_generation_stable_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, snapshot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_snapshot_demand_policies_snapshot ON planning_snapshot_demand_policies (snapshot_id)');
        $this->addSql('ALTER TABLE planning_snapshot_demand_policies ADD CONSTRAINT FK_5191E5237B39395E FOREIGN KEY (snapshot_id) REFERENCES planning_snapshots (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_snapshot_demand_policies ADD CONSTRAINT chk_snapshot_demand_policies_version CHECK (policy_version >= 1)');

        $this->addSql('CREATE TABLE planning_snapshot_demand_triggers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, trigger_stable_id UUID NOT NULL, user_stable_id UUID NOT NULL, weekday_mask SMALLINT NOT NULL, increment SMALLINT NOT NULL, demand_policy_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BFD4D3A03A61FD95 ON planning_snapshot_demand_triggers (demand_policy_id)');
        $this->addSql('ALTER TABLE planning_snapshot_demand_triggers ADD CONSTRAINT FK_BFD4D3A03A61FD95 FOREIGN KEY (demand_policy_id) REFERENCES planning_snapshot_demand_policies (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_snapshot_demand_triggers ADD CONSTRAINT chk_snapshot_demand_triggers_weekdays CHECK (weekday_mask BETWEEN 1 AND 127)');
        $this->addSql('ALTER TABLE planning_snapshot_demand_triggers ADD CONSTRAINT chk_snapshot_demand_triggers_increment CHECK (increment >= 1)');

        $this->addSql('CREATE TABLE planning_snapshot_demand_decisions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_duty_stable_id UUID NOT NULL, weekday VARCHAR(10) NOT NULL, source_user_stable_id UUID DEFAULT NULL, trigger_stable_id UUID DEFAULT NULL, day_reason VARCHAR(40) NOT NULL, required BOOLEAN DEFAULT NULL, reason VARCHAR(40) NOT NULL, snapshot_id INT NOT NULL, duty_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_snapshot_demand_decisions_duty ON planning_snapshot_demand_decisions (snapshot_id, duty_id)');
        $this->addSql('CREATE INDEX IDX_BD872E887B39395E ON planning_snapshot_demand_decisions (snapshot_id)');
        $this->addSql('CREATE INDEX IDX_BD872E883A1F9EC1 ON planning_snapshot_demand_decisions (duty_id)');
        $this->addSql('ALTER TABLE planning_snapshot_demand_decisions ADD CONSTRAINT FK_BD872E887B39395E FOREIGN KEY (snapshot_id) REFERENCES planning_snapshots (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_snapshot_demand_decisions ADD CONSTRAINT FK_BD872E883A1F9EC1 FOREIGN KEY (duty_id) REFERENCES duties (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE planning_snapshot_demand_decisions ADD CONSTRAINT chk_snapshot_demand_decisions_weekday CHECK (weekday IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))");
        $this->addSql('ALTER TABLE planning_snapshot_demand_decisions ADD CONSTRAINT chk_snapshot_demand_decisions_reasons CHECK (day_reason IN ('.self::REASONS.') AND reason IN ('.self::REASONS.'))');
        // A required unit was triggered — by this day, or by another day of its block.
        $this->addSql("ALTER TABLE planning_snapshot_demand_decisions ADD CONSTRAINT chk_snapshot_demand_decisions_required CHECK (required IS NOT TRUE OR reason IN ('TRIGGERED', 'TRIGGERED_BY_BLOCK'))");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE planning_snapshot_demand_decisions');
        $this->addSql('DROP TABLE planning_snapshot_demand_triggers');
        $this->addSql('DROP TABLE planning_snapshot_demand_policies');
    }
}
