<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Generation → edition → publication → maintenance workflow
 * (docs/decisions.md D143-D146):
 *
 * - `duty_assignment_events.new_assignment_id` becomes nullable: a removal
 *   without replacement ("Retirer l'affectation", D144) is an event whose
 *   duty has no current assignment afterwards. A CHECK keeps "neither
 *   previous nor new" impossible.
 * - `planning_publications` + `planning_publication_entries` (D143): every
 *   real diffusion, and exactly what it diffused duty by duty — the
 *   reference "Modifications non publiées" is computed against.
 *   `planning_publication_deliveries`: who was emailed, and whether the
 *   transport accepted it.
 * - `weekly_duty_reminders` (D146): idempotency log of the Saturday run.
 *
 * All four new tables are append-only (same trigger pattern as
 * duty_assignment_events, D131).
 *
 * Backfill: a Planning already PUBLISHED before this lot (D133) has no
 * publication record. One FIRST publication is created for it, dated from
 * its published period's last update and attributed to its creator, whose
 * entries are the calendar as it stands at migration time — the only
 * reference that can be reconstructed honestly (no email is re-sent).
 */
final class Version20260927090000 extends AbstractMigration
{
    private const APPEND_ONLY_TABLES = [
        'planning_publications',
        'planning_publication_entries',
        'planning_publication_deliveries',
        'weekly_duty_reminders',
    ];

    public function getDescription(): string
    {
        return 'Publication records, removals, weekly reminders (D143-D146)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE duty_assignment_events ALTER new_assignment_id DROP NOT NULL');
        $this->addSql('ALTER TABLE duty_assignment_events ADD CONSTRAINT chk_duty_assignment_events_records_something CHECK (previous_assignment_id IS NOT NULL OR new_assignment_id IS NOT NULL)');

        $this->addSql('CREATE TABLE planning_publications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, kind VARCHAR(10) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed_duty_count INT NOT NULL, planning_id INT NOT NULL, published_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_publications_stable_id ON planning_publications (stable_id)');
        $this->addSql('CREATE INDEX idx_planning_publications_planning ON planning_publications (planning_id, published_at)');
        $this->addSql('CREATE INDEX IDX_2082F8645B075477 ON planning_publications (published_by_id)');
        $this->addSql('ALTER TABLE planning_publications ADD CONSTRAINT FK_2082F8643D865311 FOREIGN KEY (planning_id) REFERENCES plannings (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_publications ADD CONSTRAINT FK_2082F8645B075477 FOREIGN KEY (published_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE planning_publications ADD CONSTRAINT chk_planning_publications_kind CHECK (kind IN ('FIRST', 'UPDATE'))");

        $this->addSql('CREATE TABLE planning_publication_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, publication_id INT NOT NULL, duty_id INT NOT NULL, team_member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_publication_entries_duty ON planning_publication_entries (publication_id, duty_id)');
        $this->addSql('CREATE INDEX IDX_6E0D7B923A1F9EC1 ON planning_publication_entries (duty_id)');
        $this->addSql('CREATE INDEX IDX_6E0D7B92C292CD19 ON planning_publication_entries (team_member_id)');
        $this->addSql('ALTER TABLE planning_publication_entries ADD CONSTRAINT FK_6E0D7B9238B217A7 FOREIGN KEY (publication_id) REFERENCES planning_publications (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_publication_entries ADD CONSTRAINT FK_6E0D7B923A1F9EC1 FOREIGN KEY (duty_id) REFERENCES duties (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_publication_entries ADD CONSTRAINT FK_6E0D7B92C292CD19 FOREIGN KEY (team_member_id) REFERENCES planning_team_members (id) ON DELETE RESTRICT NOT DEFERRABLE');

        $this->addSql('CREATE TABLE planning_publication_deliveries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sent BOOLEAN NOT NULL, attempted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, publication_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_publication_deliveries_user ON planning_publication_deliveries (publication_id, user_id)');
        $this->addSql('CREATE INDEX IDX_C800E6CBA76ED395 ON planning_publication_deliveries (user_id)');
        $this->addSql('ALTER TABLE planning_publication_deliveries ADD CONSTRAINT FK_C800E6CB38B217A7 FOREIGN KEY (publication_id) REFERENCES planning_publications (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_publication_deliveries ADD CONSTRAINT FK_C800E6CBA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');

        $this->addSql('CREATE TABLE weekly_duty_reminders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, week_start DATE NOT NULL, duty_count INT NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, planning_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_weekly_duty_reminders_week ON weekly_duty_reminders (user_id, planning_id, week_start)');
        $this->addSql('CREATE INDEX IDX_2646797C3D865311 ON weekly_duty_reminders (planning_id)');
        $this->addSql('ALTER TABLE weekly_duty_reminders ADD CONSTRAINT FK_2646797CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE weekly_duty_reminders ADD CONSTRAINT FK_2646797C3D865311 FOREIGN KEY (planning_id) REFERENCES plannings (id) ON DELETE RESTRICT NOT DEFERRABLE');

        // Backfill before the triggers exist (they only forbid UPDATE/DELETE, but keep the order obvious).
        $this->addSql(<<<'SQL'
            INSERT INTO planning_publications (stable_id, kind, published_at, changed_duty_count, planning_id, published_by_id)
            SELECT gen_random_uuid(), 'FIRST', MAX(pp.updated_at), 0, p.id, p.creator_id
            FROM plannings p
            JOIN planning_lines l ON l.planning_id = p.id AND l.active
            JOIN planning_periods pp ON pp.id = l.planning_period_id
            WHERE pp.status = 'PUBLISHED'
            GROUP BY p.id, p.creator_id
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO planning_publication_entries (publication_id, duty_id, team_member_id)
            SELECT pub.id, d.id, a.team_member_id
            FROM planning_publications pub
            JOIN planning_lines l ON l.planning_id = pub.planning_id AND l.active
            JOIN duties d ON d.planning_period_id = l.planning_period_id
            LEFT JOIN duty_assignments a ON a.duty_id = d.id AND a.current AND a.generation_id = (
                SELECT g.id FROM planning_generations g
                WHERE g.planning_period_id = l.planning_period_id AND g.status = 'COMPLETED'
                ORDER BY g.created_at DESC, g.id DESC
                LIMIT 1
            )
        SQL);

        foreach (self::APPEND_ONLY_TABLES as $table) {
            $this->addSql(<<<SQL
                CREATE FUNCTION {$table}_append_only() RETURNS trigger AS \$\$
                BEGIN
                  RAISE EXCEPTION '{$table} is append-only';
                END;
                \$\$ LANGUAGE plpgsql
            SQL);
            $this->addSql("CREATE TRIGGER trg_{$table}_append_only BEFORE UPDATE OR DELETE ON {$table} FOR EACH ROW EXECUTE FUNCTION {$table}_append_only()");
        }
    }

    public function down(Schema $schema): void
    {
        foreach (self::APPEND_ONLY_TABLES as $table) {
            $this->addSql("DROP TRIGGER trg_{$table}_append_only ON {$table}");
            $this->addSql("DROP FUNCTION {$table}_append_only()");
        }

        $this->addSql('DROP TABLE weekly_duty_reminders');
        $this->addSql('DROP TABLE planning_publication_deliveries');
        $this->addSql('DROP TABLE planning_publication_entries');
        $this->addSql('DROP TABLE planning_publications');

        // Removal events cannot be represented once the column is NOT NULL again: rolling back is
        // only possible while none exists (the trigger forbids deleting them, on purpose).
        $this->addSql('ALTER TABLE duty_assignment_events DROP CONSTRAINT chk_duty_assignment_events_records_something');
        $this->addSql('ALTER TABLE duty_assignment_events ALTER new_assignment_id SET NOT NULL');
    }
}
