<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The PDF of each publication, stored as generated (docs/decisions.md D173):
 * `planning_publication_documents`, one row per publication, append-only
 * (same trigger as the other publication tables, D143) — its bytes, a
 * SHA-256, the planning's name and period as published.
 *
 * New table only. Publications recorded before this migration get no row:
 * their PDF keeps being rendered from their frozen entries (current period
 * and names), exactly as before — rendering one now would claim a file that
 * was never the one sent.
 */
final class Version20260930120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Publication PDF stored as generated, append-only (D173)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE planning_publication_documents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content BYTEA NOT NULL, filename VARCHAR(255) NOT NULL, sha256 VARCHAR(64) NOT NULL, planning_name VARCHAR(255) NOT NULL, period_first_day DATE NOT NULL, period_last_day DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, publication_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_publication_documents_publication ON planning_publication_documents (publication_id)');
        $this->addSql('ALTER TABLE planning_publication_documents ADD CONSTRAINT FK_C2F5B06C38B217A7 FOREIGN KEY (publication_id) REFERENCES planning_publications (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE planning_publication_documents ADD CONSTRAINT chk_planning_publication_documents_sha256 CHECK (sha256 ~ '^[0-9a-f]{64}$')");
        $this->addSql('ALTER TABLE planning_publication_documents ADD CONSTRAINT chk_planning_publication_documents_period CHECK (period_first_day <= period_last_day)');
        $this->addSql(<<<'SQL'
            CREATE FUNCTION planning_publication_documents_append_only() RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'planning_publication_documents is append-only';
            END;
            $$ LANGUAGE plpgsql
        SQL);
        $this->addSql('CREATE TRIGGER trg_planning_publication_documents_append_only BEFORE UPDATE OR DELETE ON planning_publication_documents FOR EACH ROW EXECUTE FUNCTION planning_publication_documents_append_only()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE planning_publication_documents');
        $this->addSql('DROP FUNCTION planning_publication_documents_append_only()');
    }
}
