<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Registration + team invitation flow (docs/decisions.md D111-D114):
 *
 * - `users.phone_e164` — NULLABLE: accounts created before this migration
 *   (production has real ones) have no phone. "Required at registration" is
 *   enforced by RegisterUserRequest, never by a NOT NULL that would fail on
 *   existing rows. A CHECK keeps any stored phone in strict E.164 shape.
 *   Deliberately NO institution/hospital column on `users`: an affiliation
 *   changes over time and is not part of a person's durable identity
 *   (docs/decisions.md D115).
 * - `team_invitations` — an offer for an email that has no User yet, with
 *   its raw token never stored (only `token_hash`). The database itself
 *   guarantees: lower-case trimmed email, a closed set of statuses/roles,
 *   accepted_at/accepted_by_id set exactly when status = ACCEPTED, and at
 *   most one PENDING invitation per (team, email).
 * - `uniq_users_email_lower` — case-insensitive uniqueness of users.email
 *   (registration now lower-cases; older rows may not be). The migration
 *   refuses to run rather than guess if two existing accounts collide.
 *
 * Hand-written from the raw `doctrine:migrations:diff` output: as with
 * every migration since D051, the diff also proposes dropping the
 * hand-added composite FKs / partial and exclusion indexes of earlier
 * migrations (they are not representable in the ORM mapping). None of that
 * noise belongs here and none of it is applied.
 *
 * This migration was reworked before ever being committed or deployed: an
 * earlier draft also created a `hospitals` table and `users.primary_hospital_id`,
 * removed by D115. Nothing that ran anywhere else ever contained them.
 */
final class Version20260920111015 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Registration + invitations: users.phone_e164, team_invitations, case-insensitive unique user email.';
    }

    public function up(Schema $schema): void
    {
        $collisions = (int) $this->connection->fetchOne('SELECT COUNT(*) FROM (SELECT LOWER(email) FROM users GROUP BY LOWER(email) HAVING COUNT(*) > 1) c');
        $this->abortIf($collisions > 0, \sprintf('%d email address(es) exist in several capitalizations in "users": merge or rename those accounts by hand before applying this migration.', $collisions));

        // --- users ---
        $this->addSql('ALTER TABLE users ADD phone_e164 VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT chk_users_phone_e164 CHECK (phone_e164 IS NULL OR phone_e164 ~ \'^\+[1-9][0-9]{6,14}$\')');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email_lower ON users (LOWER(email))');

        // --- team_invitations ---
        $this->addSql('CREATE TABLE team_invitations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, email VARCHAR(180) NOT NULL, proposed_first_name VARCHAR(100) NOT NULL, proposed_last_name VARCHAR(100) NOT NULL, role VARCHAR(20) NOT NULL, token_hash VARCHAR(64) NOT NULL, status VARCHAR(20) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, planning_team_id INT NOT NULL, invited_by_id INT NOT NULL, accepted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_team_invitations_email ON team_invitations (email)');
        $this->addSql('CREATE INDEX idx_team_invitations_planning_team_id ON team_invitations (planning_team_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_invitations_stable_id ON team_invitations (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_invitations_token_hash ON team_invitations (token_hash)');
        $this->addSql('CREATE INDEX IDX_C817FFE3A7B4A7E3 ON team_invitations (invited_by_id)');
        $this->addSql('CREATE INDEX IDX_C817FFE320F699D9 ON team_invitations (accepted_by_id)');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT FK_C817FFE3F4018545 FOREIGN KEY (planning_team_id) REFERENCES planning_teams (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT FK_C817FFE3A7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT FK_C817FFE320F699D9 FOREIGN KEY (accepted_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');

        // At most one PENDING invitation per (team, email): a second invite
        // to the same address for the same team is "already pending", never
        // a second live token.
        $this->addSql('CREATE UNIQUE INDEX uniq_team_invitations_pending_per_team_email ON team_invitations (planning_team_id, email) WHERE (status = \'PENDING\')');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT chk_team_invitations_email_normalized CHECK (email = LOWER(BTRIM(email)) AND email <> \'\')');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT chk_team_invitations_status CHECK (status IN (\'PENDING\', \'ACCEPTED\', \'EXPIRED\', \'REVOKED\'))');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT chk_team_invitations_role CHECK (role IN (\'OWNER\', \'ADMIN\', \'MEMBER\'))');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT chk_team_invitations_token_hash CHECK (token_hash ~ \'^[0-9a-f]{64}$\')');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT chk_team_invitations_accepted_consistency CHECK ((status = \'ACCEPTED\') = (accepted_at IS NOT NULL AND accepted_by_id IS NOT NULL) AND ((accepted_at IS NULL) = (accepted_by_id IS NULL)))');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT chk_team_invitations_expiry_after_creation CHECK (expires_at > created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE team_invitations');
        $this->addSql('DROP INDEX uniq_users_email_lower');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT chk_users_phone_e164');
        $this->addSql('ALTER TABLE users DROP phone_e164');
    }
}
