<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Append-only audit of availability reminders (docs/decisions.md D127).
 *
 * Only the new table is created; the hand-written constraints of the
 * earlier lots are left alone, as in the previous migrations (D081).
 */
final class Version20260921140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add planning_availability_reminders (append-only)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE planning_availability_reminders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, channel VARCHAR(20) NOT NULL, bulk BOOLEAN NOT NULL, pending_collection_count INT NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, planning_id INT NOT NULL, recipient_id INT NOT NULL, sent_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_availability_reminders_stable_id ON planning_availability_reminders (stable_id)');
        $this->addSql('CREATE INDEX idx_planning_availability_reminders_lookup ON planning_availability_reminders (planning_id, recipient_id, sent_at)');
        $this->addSql('CREATE INDEX idx_planning_availability_reminders_recipient ON planning_availability_reminders (recipient_id)');
        $this->addSql('CREATE INDEX idx_planning_availability_reminders_sent_by ON planning_availability_reminders (sent_by_id)');
        $this->addSql('ALTER TABLE planning_availability_reminders ADD CONSTRAINT fk_planning_availability_reminders_planning FOREIGN KEY (planning_id) REFERENCES plannings (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_availability_reminders ADD CONSTRAINT fk_planning_availability_reminders_recipient FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_availability_reminders ADD CONSTRAINT fk_planning_availability_reminders_sent_by FOREIGN KEY (sent_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE planning_availability_reminders ADD CONSTRAINT chk_planning_availability_reminders_channel CHECK (channel IN ('EMAIL'))");
        $this->addSql('ALTER TABLE planning_availability_reminders ADD CONSTRAINT chk_planning_availability_reminders_pending CHECK (pending_collection_count >= 0)');

        // Append-only: a reminder that was sent is never edited nor removed.
        $this->addSql(<<<'SQL'
            CREATE FUNCTION planning_availability_reminders_append_only() RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'planning_availability_reminders is append-only';
            END;
            $$ LANGUAGE plpgsql
        SQL);
        $this->addSql('CREATE TRIGGER trg_planning_availability_reminders_append_only BEFORE UPDATE OR DELETE ON planning_availability_reminders FOR EACH ROW EXECUTE FUNCTION planning_availability_reminders_append_only()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TRIGGER trg_planning_availability_reminders_append_only ON planning_availability_reminders');
        $this->addSql('DROP FUNCTION planning_availability_reminders_append_only()');
        $this->addSql('DROP TABLE planning_availability_reminders');
    }
}
