<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * "Forgot password" flow (docs/decisions.md D013 → D141, D142):
 *
 * - `password_reset_tokens` — same shape/reasoning as `team_invitations`'
 *   token: raw value never stored, only its SHA-256 hash, unique + indexed
 *   by user. Three distinct terminal states kept apart by two separate
 *   nullable timestamps (`consumed_at`: a real reset happened;
 *   `revoked_at`: superseded by a newer request before ever being used) —
 *   a CHECK forbids a row from ever being both.
 * - `users.credentials_version` — NOT NULL, defaults to 1 so every existing
 *   row gets a real starting version with no backfill script needed. Bumped
 *   on a successful password reset; embedded in the JWT at creation and
 *   checked on every authenticated request
 *   (App\EventListener\JwtCredentialsVersionListener) so a stateless access
 *   token issued before the bump stops working immediately instead of
 *   riding out its remaining TTL.
 */
final class Version20260925090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Password reset: password_reset_tokens, users.credentials_version (D141/D142)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD credentials_version INT NOT NULL DEFAULT 1');

        $this->addSql('CREATE TABLE password_reset_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, requested_by_ip VARCHAR(45) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_password_reset_tokens_token_hash ON password_reset_tokens (token_hash)');
        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT FK_3E2F98F6A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT chk_password_reset_tokens_token_hash CHECK (token_hash ~ \'^[0-9a-f]{64}$\')');
        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT chk_password_reset_tokens_expiry_after_creation CHECK (expires_at > created_at)');
        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT chk_password_reset_tokens_not_consumed_and_revoked CHECK (consumed_at IS NULL OR revoked_at IS NULL)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE password_reset_tokens');
        $this->addSql('ALTER TABLE users DROP credentials_version');
    }
}
