<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Planning generation socle (docs/planning-generation.md): PlanningGeneration,
 * its immutable PlanningSnapshot (and children — members, participation,
 * availability, non-participation, rule set), and DutyAssignment.
 *
 * Pruned from the raw doctrine:migrations:diff output: the composite FKs,
 * EXCLUDE constraints and partial unique indexes from the planning-domain
 * hardening migration (Version20260915212500) are not represented in
 * Doctrine's ORM mapping by design (D051) — diff always proposes dropping
 * them as "unsynchronized", and that must never be applied. Only the
 * genuinely new tables/constraints for this lot are kept here.
 */
final class Version20260916084920 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Planning generation socle: PlanningGeneration, PlanningSnapshot and its children, DutyAssignment.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE duty_assignments (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              source VARCHAR(10) NOT NULL,
              locked BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              generation_id INT NOT NULL,
              duty_id INT NOT NULL,
              team_member_id INT NOT NULL,
              snapshot_member_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_duty_assignments_team_member_id ON duty_assignments (team_member_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_assignments_stable_id ON duty_assignments (stable_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_duty_assignments_generation_duty ON duty_assignments (generation_id, duty_id)
        SQL);
        $this->addSql('CREATE INDEX IDX_EF50800C553A6EC4 ON duty_assignments (generation_id)');
        $this->addSql('CREATE INDEX IDX_EF50800C3A1F9EC1 ON duty_assignments (duty_id)');
        $this->addSql('CREATE INDEX IDX_EF50800CEA03B875 ON duty_assignments (snapshot_member_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_generations (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              status VARCHAR(20) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              planning_period_id INT NOT NULL,
              created_by_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_planning_generations_planning_period_id ON planning_generations (planning_period_id)
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_generations_stable_id ON planning_generations (stable_id)');
        $this->addSql('CREATE INDEX IDX_E7FDC01AB03A8386 ON planning_generations (created_by_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_snapshot_availability_periods (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              source_availability_stable_id UUID NOT NULL,
              type VARCHAR(20) NOT NULL,
              starts_at TIMESTAMP(0)
              WITH
                TIME ZONE NOT NULL,
                ends_at TIMESTAMP(0)
              WITH
                TIME ZONE NOT NULL,
                source_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                source_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                snapshot_member_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_snapshot_availability_periods_member_id ON planning_snapshot_availability_periods (snapshot_member_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_snapshot_members (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              source_team_member_stable_id UUID NOT NULL,
              source_user_stable_id UUID NOT NULL,
              membership_start DATE NOT NULL,
              membership_end DATE DEFAULT NULL,
              role VARCHAR(20) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              snapshot_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_snapshot_members_snapshot_id ON planning_snapshot_members (snapshot_id)');
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_snapshot_members_snapshot_team_member ON planning_snapshot_members (
              snapshot_id, source_team_member_stable_id
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_snapshot_non_participation_periods (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              source_non_participation_stable_id UUID NOT NULL,
              starts_at TIMESTAMP(0)
              WITH
                TIME ZONE NOT NULL,
                ends_at TIMESTAMP(0)
              WITH
                TIME ZONE NOT NULL,
                source_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                source_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                snapshot_member_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_snapshot_non_participation_periods_member_id ON planning_snapshot_non_participation_periods (snapshot_member_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_snapshot_participation_periods (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              valid_from DATE NOT NULL,
              valid_to DATE DEFAULT NULL,
              participation_factor NUMERIC(6, 4) NOT NULL,
              change_reason VARCHAR(40) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              snapshot_member_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_snapshot_participation_periods_member_id ON planning_snapshot_participation_periods (snapshot_member_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_snapshot_rule_sets (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              source_planning_rule_set_stable_id UUID NOT NULL,
              source_version INT NOT NULL,
              configuration JSON NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              snapshot_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_snapshot_rule_sets_snapshot_id ON planning_snapshot_rule_sets (snapshot_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_snapshots (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              generation_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_planning_snapshots_generation_id ON planning_snapshots (generation_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_assignments
            ADD
              CONSTRAINT FK_EF50800C553A6EC4 FOREIGN KEY (generation_id) REFERENCES planning_generations (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_assignments
            ADD
              CONSTRAINT FK_EF50800C3A1F9EC1 FOREIGN KEY (duty_id) REFERENCES duties (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_assignments
            ADD
              CONSTRAINT FK_EF50800CC292CD19 FOREIGN KEY (team_member_id) REFERENCES team_members (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_assignments
            ADD
              CONSTRAINT FK_EF50800CEA03B875 FOREIGN KEY (snapshot_member_id) REFERENCES planning_snapshot_members (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_generations
            ADD
              CONSTRAINT FK_E7FDC01A44DBA0DD FOREIGN KEY (planning_period_id) REFERENCES planning_periods (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_generations
            ADD
              CONSTRAINT FK_E7FDC01AB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_snapshot_availability_periods
            ADD
              CONSTRAINT FK_4EB4802EA03B875 FOREIGN KEY (snapshot_member_id) REFERENCES planning_snapshot_members (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_snapshot_members
            ADD
              CONSTRAINT FK_4C55DDB07B39395E FOREIGN KEY (snapshot_id) REFERENCES planning_snapshots (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_snapshot_non_participation_periods
            ADD
              CONSTRAINT FK_A3D1E12EEA03B875 FOREIGN KEY (snapshot_member_id) REFERENCES planning_snapshot_members (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_snapshot_participation_periods
            ADD
              CONSTRAINT FK_BB5718D0EA03B875 FOREIGN KEY (snapshot_member_id) REFERENCES planning_snapshot_members (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_snapshot_rule_sets
            ADD
              CONSTRAINT FK_20175D087B39395E FOREIGN KEY (snapshot_id) REFERENCES planning_snapshots (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_snapshots
            ADD
              CONSTRAINT FK_E5C19C3E553A6EC4 FOREIGN KEY (generation_id) REFERENCES planning_generations (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE duty_assignments DROP CONSTRAINT FK_EF50800C553A6EC4');
        $this->addSql('ALTER TABLE duty_assignments DROP CONSTRAINT FK_EF50800C3A1F9EC1');
        $this->addSql('ALTER TABLE duty_assignments DROP CONSTRAINT FK_EF50800CC292CD19');
        $this->addSql('ALTER TABLE duty_assignments DROP CONSTRAINT FK_EF50800CEA03B875');
        $this->addSql('ALTER TABLE planning_generations DROP CONSTRAINT FK_E7FDC01A44DBA0DD');
        $this->addSql('ALTER TABLE planning_generations DROP CONSTRAINT FK_E7FDC01AB03A8386');
        $this->addSql('ALTER TABLE planning_snapshot_availability_periods DROP CONSTRAINT FK_4EB4802EA03B875');
        $this->addSql('ALTER TABLE planning_snapshot_members DROP CONSTRAINT FK_4C55DDB07B39395E');
        $this->addSql('ALTER TABLE planning_snapshot_non_participation_periods DROP CONSTRAINT FK_A3D1E12EEA03B875');
        $this->addSql('ALTER TABLE planning_snapshot_participation_periods DROP CONSTRAINT FK_BB5718D0EA03B875');
        $this->addSql('ALTER TABLE planning_snapshot_rule_sets DROP CONSTRAINT FK_20175D087B39395E');
        $this->addSql('ALTER TABLE planning_snapshots DROP CONSTRAINT FK_E5C19C3E553A6EC4');
        $this->addSql('DROP TABLE duty_assignments');
        $this->addSql('DROP TABLE planning_generations');
        $this->addSql('DROP TABLE planning_snapshot_availability_periods');
        $this->addSql('DROP TABLE planning_snapshot_members');
        $this->addSql('DROP TABLE planning_snapshot_non_participation_periods');
        $this->addSql('DROP TABLE planning_snapshot_participation_periods');
        $this->addSql('DROP TABLE planning_snapshot_rule_sets');
        $this->addSql('DROP TABLE planning_snapshots');
    }
}
