<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Planning aggregate socle (docs/planning.md): Planning and PlanningLine —
 * the user-visible grouping layer sitting above the existing mono-team
 * engine (PlanningPeriod/FairnessPeriod/Duty/... all unchanged).
 *
 * Pruned from the raw doctrine:migrations:diff output: the composite FKs/
 * EXCLUDE constraints/partial unique indexes from earlier hardening
 * migrations are not represented in Doctrine's ORM mapping by design
 * (D051) — diff always proposes dropping them as "unsynchronized", and
 * that must never be applied (same situation as Version20260916084920 and
 * Version20260916095723). The team_members open-membership index also
 * appears in that noise — its real replacement (one row per User, not per
 * (Team, User)) is a deliberate, separate migration
 * (Version20260916123301, D072), not part of this cleanup.
 */
final class Version20260916123259 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Planning aggregate socle: Planning, PlanningLine (PRIMARY/SECONDARY, one Team per line within a Planning).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_lines (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              name VARCHAR(150) NOT NULL,
              type VARCHAR(20) NOT NULL,
              position INT NOT NULL,
              active BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              planning_id INT NOT NULL,
              team_id INT NOT NULL,
              planning_period_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_planning_lines_planning_id ON planning_lines (planning_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_lines_stable_id ON planning_lines (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_lines_planning_team ON planning_lines (planning_id, team_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_planning_lines_planning_period_id ON planning_lines (planning_period_id)
        SQL);
        $this->addSql('CREATE INDEX IDX_DEAD3609296CD8AE ON planning_lines (team_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE plannings (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              name VARCHAR(150) NOT NULL,
              starts_at DATE NOT NULL,
              ends_at DATE NOT NULL,
              timezone VARCHAR(64) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              creator_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_plannings_creator_id ON plannings (creator_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_plannings_stable_id ON plannings (stable_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_lines
            ADD
              CONSTRAINT FK_DEAD36093D865311 FOREIGN KEY (planning_id) REFERENCES plannings (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_lines
            ADD
              CONSTRAINT FK_DEAD3609296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_lines
            ADD
              CONSTRAINT FK_DEAD360944DBA0DD FOREIGN KEY (planning_period_id) REFERENCES planning_periods (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              plannings
            ADD
              CONSTRAINT FK_4F04019D61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE planning_lines DROP CONSTRAINT FK_DEAD36093D865311');
        $this->addSql('ALTER TABLE planning_lines DROP CONSTRAINT FK_DEAD3609296CD8AE');
        $this->addSql('ALTER TABLE planning_lines DROP CONSTRAINT FK_DEAD360944DBA0DD');
        $this->addSql('ALTER TABLE plannings DROP CONSTRAINT FK_4F04019D61220EA6');
        $this->addSql('DROP TABLE planning_lines');
        $this->addSql('DROP TABLE plannings');
    }
}
