<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * SurgicalHub leave in the personal calendar (docs/surgicalhub-integration.md §6.1,
 * docs/decisions.md D183):
 * - `user_availability_periods.source` (MANUAL | SURGICAL_HUB), every existing
 *   row MANUAL through the column default;
 * - the no-overlap/no-touch exclusion constraint becomes partial: it keeps
 *   binding MANUAL periods to each other exactly as before, and no longer
 *   applies to imported ones (a person is unavailable on the union). Dropped
 *   and recreated in the same transaction: existing rows are all MANUAL and
 *   already satisfy it, so the new constraint validates without data change;
 * - `surgical_hub_imported_leaves`: which SurgicalHub absence each imported
 *   period mirrors — never two periods for the same absence;
 * - `planning_snapshot_availability_periods.provenance`, copied at snapshot
 *   time (existing frozen rows were all manual: the default is their truth).
 *
 * Only additive DDL besides the constraint swap: no UPDATE, no DELETE.
 */
final class Version20261010120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'SurgicalHub leave: period provenance, partial no-overlap constraint, imported leave mapping (D183)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE user_availability_periods ADD source VARCHAR(20) DEFAULT 'MANUAL' NOT NULL");
        $this->addSql("ALTER TABLE user_availability_periods ADD CONSTRAINT chk_user_availability_periods_source CHECK (source IN ('MANUAL', 'SURGICAL_HUB'))");
        $this->addSql('ALTER TABLE user_availability_periods DROP CONSTRAINT excl_user_availability_periods_no_overlap');
        $this->addSql(<<<'SQL'
            ALTER TABLE user_availability_periods ADD CONSTRAINT excl_user_availability_periods_no_overlap
              EXCLUDE USING gist (user_id WITH =, type WITH =, tstzrange(starts_at, ends_at, '[]') WITH &&)
              WHERE (source = 'MANUAL')
        SQL);

        $this->addSql("ALTER TABLE planning_snapshot_availability_periods ADD provenance VARCHAR(20) DEFAULT 'MANUAL' NOT NULL");
        $this->addSql("ALTER TABLE planning_snapshot_availability_periods ADD CONSTRAINT chk_snapshot_availability_periods_provenance CHECK (provenance IN ('MANUAL', 'SURGICAL_HUB'))");

        $this->addSql('CREATE TABLE surgical_hub_imported_leaves (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, surgical_hub_user_id VARCHAR(64) NOT NULL, external_absence_id VARCHAR(64) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, first_imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, link_id INT NOT NULL, availability_period_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_surgical_hub_imported_leaves_absence ON surgical_hub_imported_leaves (user_id, surgical_hub_user_id, external_absence_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_surgical_hub_imported_leaves_period ON surgical_hub_imported_leaves (availability_period_id)');
        $this->addSql('CREATE INDEX idx_surgical_hub_imported_leaves_link_id ON surgical_hub_imported_leaves (link_id)');
        $this->addSql('ALTER TABLE surgical_hub_imported_leaves ADD CONSTRAINT fk_surgical_hub_imported_leaves_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE surgical_hub_imported_leaves ADD CONSTRAINT fk_surgical_hub_imported_leaves_link FOREIGN KEY (link_id) REFERENCES surgical_hub_links (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE surgical_hub_imported_leaves ADD CONSTRAINT fk_surgical_hub_imported_leaves_period FOREIGN KEY (availability_period_id) REFERENCES user_availability_periods (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE surgical_hub_imported_leaves ADD CONSTRAINT chk_surgical_hub_imported_leaves_dates CHECK (end_date >= start_date)');
    }

    public function down(Schema $schema): void
    {
        // Imported periods must go first: the restored constraint binds every row again.
        $this->addSql("DELETE FROM user_availability_periods WHERE source <> 'MANUAL'");
        $this->addSql('DROP TABLE surgical_hub_imported_leaves');
        $this->addSql('ALTER TABLE planning_snapshot_availability_periods DROP CONSTRAINT chk_snapshot_availability_periods_provenance');
        $this->addSql('ALTER TABLE planning_snapshot_availability_periods DROP provenance');
        $this->addSql('ALTER TABLE user_availability_periods DROP CONSTRAINT excl_user_availability_periods_no_overlap');
        $this->addSql(<<<'SQL'
            ALTER TABLE user_availability_periods ADD CONSTRAINT excl_user_availability_periods_no_overlap
              EXCLUDE USING gist (user_id WITH =, type WITH =, tstzrange(starts_at, ends_at, '[]') WITH &&)
        SQL);
        $this->addSql('ALTER TABLE user_availability_periods DROP CONSTRAINT chk_user_availability_periods_source');
        $this->addSql('ALTER TABLE user_availability_periods DROP source');
    }
}
