<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260915212445 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Planning domain socle: teams, membership, participation history, fairness/planning periods, duty types/patterns/instances, versioned rule sets. Also backfills a stable UUID identifier on users.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE duties (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              local_date DATE NOT NULL,
              starts_at TIMESTAMP(0)
              WITH
                TIME ZONE NOT NULL,
                ends_at TIMESTAMP(0)
              WITH
                TIME ZONE NOT NULL,
                timezone VARCHAR(64) NOT NULL,
                demand_type VARCHAR(20) NOT NULL,
                criticality VARCHAR(20) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                team_id INT NOT NULL,
                planning_period_id INT NOT NULL,
                duty_type_id INT NOT NULL,
                group_instance_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_duties_planning_period_id ON duties (planning_period_id)');
        $this->addSql('CREATE INDEX idx_duties_local_date ON duties (local_date)');
        $this->addSql('CREATE INDEX idx_duties_group_instance_id ON duties (group_instance_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duties_stable_id ON duties (stable_id)');
        $this->addSql('CREATE INDEX IDX_6148FB50296CD8AE ON duties (team_id)');
        $this->addSql('CREATE INDEX IDX_6148FB50A8708D42 ON duties (duty_type_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE duty_group_instances (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              anchor_date DATE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              team_id INT NOT NULL,
              planning_period_id INT NOT NULL,
              pattern_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_duty_group_instances_planning_period_id ON duty_group_instances (planning_period_id)
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_group_instances_stable_id ON duty_group_instances (stable_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_duty_group_instances_planning_period_id ON duty_group_instances (id, planning_period_id)
        SQL);
        $this->addSql('CREATE INDEX IDX_C44E5594296CD8AE ON duty_group_instances (team_id)');
        $this->addSql('CREATE INDEX IDX_C44E5594F734A20F ON duty_group_instances (pattern_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE duty_pattern_components (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              day_offset SMALLINT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              pattern_id INT NOT NULL,
              team_id INT NOT NULL,
              duty_type_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_pattern_components_offset ON duty_pattern_components (pattern_id, day_offset)
        SQL);
        $this->addSql('CREATE INDEX IDX_8A8E7E04F734A20F ON duty_pattern_components (pattern_id)');
        $this->addSql('CREATE INDEX IDX_8A8E7E04296CD8AE ON duty_pattern_components (team_id)');
        $this->addSql('CREATE INDEX IDX_8A8E7E04A8708D42 ON duty_pattern_components (duty_type_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE duty_patterns (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              code VARCHAR(50) NOT NULL,
              name VARCHAR(150) NOT NULL,
              active BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              team_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_patterns_stable_id ON duty_patterns (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_patterns_team_code ON duty_patterns (team_id, code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_patterns_id_team_id ON duty_patterns (id, team_id)');
        $this->addSql('CREATE INDEX IDX_E0140393296CD8AE ON duty_patterns (team_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE duty_types (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              code VARCHAR(50) NOT NULL,
              name VARCHAR(150) NOT NULL,
              active BOOLEAN NOT NULL,
              workload_value NUMERIC(6, 2) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              team_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_types_stable_id ON duty_types (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_types_team_code ON duty_types (team_id, code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_types_id_team_id ON duty_types (id, team_id)');
        $this->addSql('CREATE INDEX IDX_B292847B296CD8AE ON duty_types (team_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE fairness_periods (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(150) NOT NULL,
              starts_at DATE NOT NULL,
              ends_at DATE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              team_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_fairness_periods_team_id ON fairness_periods (team_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_fairness_periods_id_team_id ON fairness_periods (id, team_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_periods (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              name VARCHAR(150) NOT NULL,
              starts_at DATE NOT NULL,
              ends_at DATE NOT NULL,
              status VARCHAR(20) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              team_id INT NOT NULL,
              fairness_period_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_planning_periods_team_id ON planning_periods (team_id)');
        $this->addSql('CREATE INDEX idx_planning_periods_fairness_period_id ON planning_periods (fairness_period_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_periods_stable_id ON planning_periods (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_periods_id_team_id ON planning_periods (id, team_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_rule_sets (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              version INT NOT NULL,
              status VARCHAR(20) NOT NULL,
              effective_from DATE NOT NULL,
              configuration JSON NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              team_id INT NOT NULL,
              created_by_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_rule_sets_stable_id ON planning_rule_sets (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_rule_sets_team_version ON planning_rule_sets (team_id, version)');
        $this->addSql('CREATE INDEX IDX_6F19C0A5296CD8AE ON planning_rule_sets (team_id)');
        $this->addSql('CREATE INDEX IDX_6F19C0A5B03A8386 ON planning_rule_sets (created_by_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE team_member_participation_periods (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              valid_from DATE NOT NULL,
              valid_to DATE DEFAULT NULL,
              participation_factor NUMERIC(6, 4) NOT NULL,
              change_reason VARCHAR(40) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              team_member_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_participation_periods_team_member_id ON team_member_participation_periods (team_member_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE team_members (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              role VARCHAR(20) NOT NULL,
              membership_start DATE NOT NULL,
              membership_end DATE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              team_id INT NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_team_members_team_id ON team_members (team_id)');
        $this->addSql('CREATE INDEX idx_team_members_user_id ON team_members (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE teams (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              stable_id UUID NOT NULL,
              name VARCHAR(150) NOT NULL,
              slug VARCHAR(150) NOT NULL,
              timezone VARCHAR(64) NOT NULL,
              active BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_teams_stable_id ON teams (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_teams_slug ON teams (slug)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duties
            ADD
              CONSTRAINT FK_6148FB50296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duties
            ADD
              CONSTRAINT FK_6148FB5044DBA0DD FOREIGN KEY (planning_period_id) REFERENCES planning_periods (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duties
            ADD
              CONSTRAINT FK_6148FB50A8708D42 FOREIGN KEY (duty_type_id) REFERENCES duty_types (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duties
            ADD
              CONSTRAINT FK_6148FB501FE96DDC FOREIGN KEY (group_instance_id) REFERENCES duty_group_instances (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_group_instances
            ADD
              CONSTRAINT FK_C44E5594296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_group_instances
            ADD
              CONSTRAINT FK_C44E559444DBA0DD FOREIGN KEY (planning_period_id) REFERENCES planning_periods (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_group_instances
            ADD
              CONSTRAINT FK_C44E5594F734A20F FOREIGN KEY (pattern_id) REFERENCES duty_patterns (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_pattern_components
            ADD
              CONSTRAINT FK_8A8E7E04F734A20F FOREIGN KEY (pattern_id) REFERENCES duty_patterns (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_pattern_components
            ADD
              CONSTRAINT FK_8A8E7E04296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_pattern_components
            ADD
              CONSTRAINT FK_8A8E7E04A8708D42 FOREIGN KEY (duty_type_id) REFERENCES duty_types (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_patterns
            ADD
              CONSTRAINT FK_E0140393296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              duty_types
            ADD
              CONSTRAINT FK_B292847B296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              fairness_periods
            ADD
              CONSTRAINT FK_C7406ACA296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_periods
            ADD
              CONSTRAINT FK_BA7AC549296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_periods
            ADD
              CONSTRAINT FK_BA7AC549121CA816 FOREIGN KEY (fairness_period_id) REFERENCES fairness_periods (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_rule_sets
            ADD
              CONSTRAINT FK_6F19C0A5296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_rule_sets
            ADD
              CONSTRAINT FK_6F19C0A5B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              team_member_participation_periods
            ADD
              CONSTRAINT FK_A903DFE0C292CD19 FOREIGN KEY (team_member_id) REFERENCES team_members (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              team_members
            ADD
              CONSTRAINT FK_BAD9A3C8296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              team_members
            ADD
              CONSTRAINT FK_BAD9A3C8A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        // Added nullable first and backfilled: existing rows predate this
        // column, and gen_random_uuid() (built into PostgreSQL 13+, no
        // extension needed) gives each of them a real UUIDv4 rather than a
        // dummy shared placeholder that would make stable_id's uniqueness
        // constraint fail as soon as a second pre-existing row exists.
        $this->addSql('ALTER TABLE users ADD stable_id UUID DEFAULT NULL');
        $this->addSql('UPDATE users SET stable_id = gen_random_uuid() WHERE stable_id IS NULL');
        $this->addSql('ALTER TABLE users ALTER COLUMN stable_id SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_stable_id ON users (stable_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE duties DROP CONSTRAINT FK_6148FB50296CD8AE');
        $this->addSql('ALTER TABLE duties DROP CONSTRAINT FK_6148FB5044DBA0DD');
        $this->addSql('ALTER TABLE duties DROP CONSTRAINT FK_6148FB50A8708D42');
        $this->addSql('ALTER TABLE duties DROP CONSTRAINT FK_6148FB501FE96DDC');
        $this->addSql('ALTER TABLE duty_group_instances DROP CONSTRAINT FK_C44E5594296CD8AE');
        $this->addSql('ALTER TABLE duty_group_instances DROP CONSTRAINT FK_C44E559444DBA0DD');
        $this->addSql('ALTER TABLE duty_group_instances DROP CONSTRAINT FK_C44E5594F734A20F');
        $this->addSql('ALTER TABLE duty_pattern_components DROP CONSTRAINT FK_8A8E7E04F734A20F');
        $this->addSql('ALTER TABLE duty_pattern_components DROP CONSTRAINT FK_8A8E7E04296CD8AE');
        $this->addSql('ALTER TABLE duty_pattern_components DROP CONSTRAINT FK_8A8E7E04A8708D42');
        $this->addSql('ALTER TABLE duty_patterns DROP CONSTRAINT FK_E0140393296CD8AE');
        $this->addSql('ALTER TABLE duty_types DROP CONSTRAINT FK_B292847B296CD8AE');
        $this->addSql('ALTER TABLE fairness_periods DROP CONSTRAINT FK_C7406ACA296CD8AE');
        $this->addSql('ALTER TABLE planning_periods DROP CONSTRAINT FK_BA7AC549296CD8AE');
        $this->addSql('ALTER TABLE planning_periods DROP CONSTRAINT FK_BA7AC549121CA816');
        $this->addSql('ALTER TABLE planning_rule_sets DROP CONSTRAINT FK_6F19C0A5296CD8AE');
        $this->addSql('ALTER TABLE planning_rule_sets DROP CONSTRAINT FK_6F19C0A5B03A8386');
        $this->addSql('ALTER TABLE team_member_participation_periods DROP CONSTRAINT FK_A903DFE0C292CD19');
        $this->addSql('ALTER TABLE team_members DROP CONSTRAINT FK_BAD9A3C8296CD8AE');
        $this->addSql('ALTER TABLE team_members DROP CONSTRAINT FK_BAD9A3C8A76ED395');
        $this->addSql('DROP TABLE duties');
        $this->addSql('DROP TABLE duty_group_instances');
        $this->addSql('DROP TABLE duty_pattern_components');
        $this->addSql('DROP TABLE duty_patterns');
        $this->addSql('DROP TABLE duty_types');
        $this->addSql('DROP TABLE fairness_periods');
        $this->addSql('DROP TABLE planning_periods');
        $this->addSql('DROP TABLE planning_rule_sets');
        $this->addSql('DROP TABLE team_member_participation_periods');
        $this->addSql('DROP TABLE team_members');
        $this->addSql('DROP TABLE teams');
        $this->addSql('DROP INDEX uniq_users_stable_id');
        $this->addSql('ALTER TABLE users DROP stable_id');
    }
}
