<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Cross-line constraints on the same person (docs/decisions.md D161):
 * `planning_snapshot_external_commitments` freezes, per snapshot, the
 * duties its people already hold on the lines solved before this one —
 * values only (stable ids, instants, the owning generation's rest
 * thresholds), never a live relation, so an old generation keeps
 * explaining its own solve after the other line's calendar changes.
 *
 * New table only: existing snapshots simply have no commitment, which is
 * exactly what they were solved with.
 */
final class Version20260928120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Frozen cross-line commitments of a planning snapshot (D161)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE planning_snapshot_external_commitments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_user_stable_id UUID NOT NULL, source_line_stable_id UUID NOT NULL, source_generation_stable_id UUID NOT NULL, source_duty_stable_id UUID NOT NULL, starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, source_legal_min_rest_hours INT DEFAULT NULL, source_team_min_rest_hours INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, snapshot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_snapshot_external_commitments_snapshot_user ON planning_snapshot_external_commitments (snapshot_id, source_user_stable_id)');
        $this->addSql('CREATE INDEX IDX_C36133BF7B39395E ON planning_snapshot_external_commitments (snapshot_id)');
        $this->addSql('ALTER TABLE planning_snapshot_external_commitments ADD CONSTRAINT FK_C36133BF7B39395E FOREIGN KEY (snapshot_id) REFERENCES planning_snapshots (id) ON DELETE CASCADE NOT DEFERRABLE');
        // Defense in depth, same style as the other snapshot tables: already checked by the constructor.
        $this->addSql('ALTER TABLE planning_snapshot_external_commitments ADD CONSTRAINT chk_snapshot_external_commitments_interval CHECK (ends_at > starts_at)');
        $this->addSql('ALTER TABLE planning_snapshot_external_commitments ADD CONSTRAINT chk_snapshot_external_commitments_rest_hours CHECK ((source_legal_min_rest_hours IS NULL OR source_legal_min_rest_hours > 0) AND (source_team_min_rest_hours IS NULL OR source_team_min_rest_hours > 0))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE planning_snapshot_external_commitments');
    }
}
