<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Availability collections (docs/availability-collection.md, D120-D124):
 * "who has reviewed their availabilities for this slice of a planning".
 *
 * Only the new tables are created. `doctrine:migrations:diff` also proposes
 * dropping every hand-written constraint of the earlier lots (composite
 * foreign keys, exclusion constraints, partial indexes — the ORM mapping
 * cannot represent them, docs/decisions.md D081); those proposals are
 * deliberately discarded here, as in the previous migrations.
 */
final class Version20260921053604 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add availability_collections and availability_collection_responses';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE availability_collections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, starts_at DATE NOT NULL, ends_at DATE NOT NULL, opened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deadline DATE DEFAULT NULL, status VARCHAR(20) NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, planning_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_availability_collections_planning_id ON availability_collections (planning_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_availability_collections_stable_id ON availability_collections (stable_id)');
        $this->addSql('CREATE INDEX IDX_BF513B4FB03A8386 ON availability_collections (created_by_id)');
        $this->addSql('ALTER TABLE availability_collections ADD CONSTRAINT FK_BF513B4F3D865311 FOREIGN KEY (planning_id) REFERENCES plannings (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE availability_collections ADD CONSTRAINT FK_BF513B4FB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');

        $this->addSql('CREATE TABLE availability_collection_responses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stable_id UUID NOT NULL, acknowledged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, acknowledgement_kind VARCHAR(30) DEFAULT NULL, last_availability_change_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, withdrawn_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, collection_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_availability_collection_responses_user_id ON availability_collection_responses (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_availability_collection_responses_stable_id ON availability_collection_responses (stable_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_availability_collection_responses_collection_user ON availability_collection_responses (collection_id, user_id)');
        $this->addSql('CREATE INDEX IDX_D38CBC94514956FD ON availability_collection_responses (collection_id)');
        $this->addSql('ALTER TABLE availability_collection_responses ADD CONSTRAINT FK_D38CBC94514956FD FOREIGN KEY (collection_id) REFERENCES availability_collections (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE availability_collection_responses ADD CONSTRAINT FK_D38CBC94A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');

        // Hand-written invariants the ORM mapping cannot express. btree_gist is
        // already installed by the FairnessPeriod migration (D049).
        $this->addSql('ALTER TABLE availability_collections ADD CONSTRAINT chk_availability_collections_dates CHECK (ends_at > starts_at)');
        $this->addSql("ALTER TABLE availability_collections ADD CONSTRAINT chk_availability_collections_status CHECK (status IN ('OPEN', 'CLOSED'))");
        // No two collections of one planning may ask about the same date: a
        // date is collected once, an extension only ever opens the new dates.
        $this->addSql(<<<'SQL'
            ALTER TABLE availability_collections ADD CONSTRAINT excl_availability_collections_no_overlap
              EXCLUDE USING gist (planning_id WITH =, daterange(starts_at, ends_at, '[)') WITH &&)
        SQL);
        // "Answered" is one explicit event: a timestamp and its kind, together or not at all.
        $this->addSql('ALTER TABLE availability_collection_responses ADD CONSTRAINT chk_availability_collection_responses_ack CHECK ((acknowledged_at IS NULL) = (acknowledgement_kind IS NULL))');
        $this->addSql("ALTER TABLE availability_collection_responses ADD CONSTRAINT chk_availability_collection_responses_kind CHECK (acknowledgement_kind IS NULL OR acknowledgement_kind IN ('CONFIRMED', 'NO_UNAVAILABILITY'))");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE availability_collection_responses');
        $this->addSql('DROP TABLE availability_collections');
    }
}
